Repository DSharpPlus/DSharpPlus, pull requests merged in 2018-08, with the labels that each got.

#337 Fix #314 - Timestamp property throws ArgumentNullException
  DSharpPlus/Entities/DiscordMessage.cs
Labels: bug, core

#336 Add an overload for GetReactionsAsync in DiscordRestClient
  DSharpPlus.Rest/DiscordRestClient.cs
Labels: enhancement

#340 Added MayStartNext and fixed TrackExceptionEvent not being fired
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkUtil.cs
Labels: enhancement, lavalink

#346 Implement GuildBefore value in GuildUpdated event
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/EventArgs/GuildUpdateEventArgs.cs
Labels: core, new-features

#342 Fix activity game party size exploit/bug
  DSharpPlus/Entities/DiscordActivity.cs
  DSharpPlus/Net/Abstractions/TransportActivity.cs
Labels: bug, core

#347 Fix incorrect implementation of RoleCheckMode.All
  DSharpPlus.CommandsNext/Attributes/RequireRolesAttribute.cs
Labels: bug, commandsnext

#351 Fix CloneAsync in DiscordChannel that was throwing a bad request.
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordChannel.cs
Labels: bug, core

#350 Assign skeleton object to Target in DiscordAuditLogObjects when the target couldn't be pulled from cache
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Entities/DiscordGuild.cs
Labels: core, enhancement

#352 Undisgust the build script
  appveyor.yml
Labels: enhancement

#353 Removed unnecessary Where condition in ModifyPositionAsync that broke it Fixes #299
  DSharpPlus/Entities/DiscordRole.cs
Labels: bug, core
