Repository DSharpPlus/DSharpPlus, pull requests merged in 2018-10, with the labels that each got.

#365 Allows for sending empty embeds instead of causing a bad request.
  DSharpPlus/Entities/DiscordEmbedBuilder.cs
Labels: bug, core

#366 Fixed embed builder's fields and cleaned up code.
  DSharpPlus/Entities/DiscordEmbed.cs
  DSharpPlus/Entities/DiscordEmbedBuilder.cs
  DSharpPlus/Entities/DiscordEmbedFooter.cs
  DSharpPlus/Entities/DiscordEmbedImage.cs
  DSharpPlus/Entities/DiscordEmbedThumbnail.cs
Labels: core, enhancement

#367 Fix Lavalink sometimes not decoding tracks properly
  DSharpPlus.Lavalink/LavalinkUtil.cs
Labels: bug, lavalink
