Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-12, with the labels that each got.

#485 Fixed status not reapplying after disconnect.
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Net/Abstractions/StatusUpdate.cs
Labels: bug, core

#486 Added support for message flags
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Enums/MessageActivityType.cs
  DSharpPlus/Enums/MessageFlag.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, new-features

#495 Reapplying status hotfix
  DSharpPlus/DiscordClient.cs
Labels: bug, core

#497 Fixed a couple DiscordPresence properties returning null
  DSharpPlus/DiscordClient.cs
Labels: bug, core

#498 Implemented custom statuses
  DSharpPlus/Entities/DiscordActivity.cs
  DSharpPlus/Net/Abstractions/TransportActivity.cs
Labels: core, new-features

#500 Fix NRE when ReactionCollectRequest is disposed more than once
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
Labels: bug, interactivity

#489 Allow interactivity page set values to property setters.
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
Labels: interactivity
