Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-08, with the labels that each got.

#459 Update docs debug symbols url [ci skip]
  docs/articles/advanced/debug_symbols.md
Labels: enhancement

#461 Fix DocFX generation: add Explicit Interface Implementation support
  docs/dsplus/plugins/HSNXT.DocFx.CustomMemberIndexer.dll
Labels: bug, docs

#463 [WIP] Add support for new channel types.
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Enums/ChannelType.cs
  DSharpPlus/Net/Models/ChannelEditModel.cs
Labels: core, new-features
