Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-04, with the labels that each got.

#413 Fix #378: Rename PresenceUpdate from PRESENCE_UPDATEED to PRESENCE_UPDATED
  DSharpPlus/DiscordClient.cs
Labels: bug, core

#416 Update debugging guide
  docs/articles/advanced/debug_symbols.md
Labels: docs, enhancement

#412 Make entities fully thread-safe
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
  DSharpPlus.CommandsNext/EventArgs/CommandContext.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordEmoji.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordRole.cs
  DSharpPlus/Entities/DiscordVoiceState.cs
  DSharpPlus/EventArgs/GuildEmojisUpdateEventArgs.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Serialization/SnowflakeArrayAsDictionaryJsonConverter.cs
  DSharpPlus/ReadOnlyConcurrentDictionary.cs
  DSharpPlus/ReadOnlySet.cs
Labels: core, enhancement

#408 Implement client_status, activities, other docs fixes, organize serializers, Optional<T> overhaul (fix #381)
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
  DSharpPlus.CommandsNext/Converters/EnumConverter.cs
  DSharpPlus.CommandsNext/Converters/NullableConverter.cs
  DSharpPlus.CommandsNext/Converters/NumericConverters.cs
  DSharpPlus.CommandsNext/Converters/StringConverter.cs
  DSharpPlus.CommandsNext/Converters/TimeConverters.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Entities/DiscordActivity.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordEmbed.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordPresence.cs
  DSharpPlus/Entities/DiscordUri.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Entities/Optional.cs
  DSharpPlus/Net/Serialization/DiscordJson.cs
Labels: bug, core, enhancement, new-features

#418 Rewrite/interactivity
  DSharpPlus.CommandsNext/DSharpPlus.CommandsNext.csproj
  DSharpPlus.Interactivity/Concurrency/ConcurrentHashSet.cs
  DSharpPlus.Interactivity/Concurrency/PlatformHelper.cs
  DSharpPlus.Interactivity/DSharpPlus.Interactivity.csproj
  DSharpPlus.Interactivity/Entities/MessageContext.cs
  DSharpPlus.Interactivity/Entities/PaginationEmojis.cs
  DSharpPlus.Interactivity/Entities/ReactionCollectionContext.cs
  DSharpPlus.Interactivity/Entities/ReactionContext.cs
  DSharpPlus.Interactivity/Entities/TypingContext.cs
  DSharpPlus.Interactivity/Enums/PaginationBehaviour.cs
  DSharpPlus.Interactivity/Enums/PollBehaviour.cs
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/EventHandling/Requests/CollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/MatchRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PollRequest.cs
  DSharpPlus.Interactivity/Extensions.cs
  DSharpPlus.Interactivity/InteractivityConfiguration.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Interactivity/InteractivityExtensionMethods.cs
  DSharpPlus.Interactivity/InteractivityResult.cs
  DSharpPlus.Lavalink/DSharpPlus.Lavalink.csproj
  DSharpPlus.Rest/DSharpPlus.Rest.csproj
  DSharpPlus.Test/BeeMovie.cs
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.Test/TestBotDynamicCommands.cs
  DSharpPlus.VoiceNext/DSharpPlus.VoiceNext.csproj
  DSharpPlus.WebSocket.WebSocket4Net/DSharpPlus.WebSocket.WebSocket4Net.csproj
  DSharpPlus.WebSocket.WebSocket4NetCore/DSharpPlus.WebSocket.WebSocket4NetCore.csproj
  DSharpPlus.WebSocket.WebSocketSharp/DSharpPlus.WebSocket.WebSocketSharp.csproj
  DSharpPlus/DSharpPlus.csproj
Labels: big-change, enhancement, interactivity, new-features

#420 Fix GetResult call on async method in an async context.
  DSharpPlus.Rest/DiscordRestClient.cs
Labels: bug

#421 Adds the way to specify the topic on channel creating.
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Net/Abstractions/RestChannelPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Models/ChannelEditModel.cs
Labels: core, new-features

#422 Adds support for sending file and multiple files with a webhook.
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/DiscordWebhookClient.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, new-features
