Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-03, with the labels that each got.

#396 Fixes #392 - DmHelp property
  DSharpPlus.CommandsNext/CommandsNextConfiguration.cs
Labels: bug, commandsnext

#397 Fast-track getting a channel's parent if it does not exist
  DSharpPlus/Entities/DiscordChannel.cs
Labels: core, enhancement

#399 Fix GetMessagesAsync (and possibly others) returning messages with no channel
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core

#400 Revert #399 "Fix GetMessagesAsync (and possibly others) returning messages with no channel"
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core

#405 Complete emoji update
  DSharpPlus/Entities/DiscordEmoji.EmojiUtils.cs
Labels: core

#402 Enormous documentation overhaul
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Entities/DiscordMember.cs
  docs/docfx.json
  docs/dsplus/ManagedReference.extension.js
  docs/dsplus/partials/class.tmpl.partial
  docs/dsplus/partials/customMREFContent.tmpl.partial
  docs/dsplus/plugins/CsQuery.dll
  docs/dsplus/plugins/HSNXT.DocFx.CustomMemberIndexer.dll
  docs/dsplus/plugins/LICENSE.CsQuery.txt
  docs/dsplus/styles/docfx.css
  docs/dsplus/styles/docfx.js
  docs/dsplus/styles/search-worker.js
Labels: big-change, docs

#404 Use property/event expression body style wherever possible
  DSharpPlus/DiscordClient.cs
  DSharpPlus/DiscordShardedClient.cs
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Net/Abstractions/TransportActivity.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
  DSharpPlus/Net/WebSocket/WebSocketClient2.cs
Labels: core

#403 Fix documentation for UserUpdated...
  DSharpPlus/DiscordClient.cs
Labels: core, docs

#401 Replaces instances of ContainsKey+hash lookup with TryGetValue
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordUser.cs
Labels: core, enhancement

#406 Add DocFX license
  docs/dsplus/plugins/LICENSE.DocFX.txt
Labels: docs, enhancement
