Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-02, with the labels that each got.

#384 Remove unnecessary guild redownloading (#383)
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/BaseDiscordClient.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Enums/PremiumType.cs
  DSharpPlus/Net/Abstractions/TransportUser.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core

#388 Add Locale property to DiscordUser/DiscordMember
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Net/Abstractions/TransportUser.cs
Labels: core, new-features

#386 Adds option to get rest user's permissions in guild.
  DSharpPlus/Entities/DiscordGuild.cs
Labels: core, new-features

#390 removed useless line and commented out code
  DSharpPlus/DiscordClient.cs
Labels: core, enhancement

#391 Update DiscordConnection
  DSharpPlus/Entities/DiscordConnection.cs
Labels: core, new-features

#393 Add missing bot-to-bot DM sanity checks
  DSharpPlus/Entities/DiscordMember.cs
Labels: core, enhancement
