Repository DSharpPlus/DSharpPlus, pull requests merged in 2019-10, with the labels that each got.

#478 Fix #477 and fix #431: Prevent static constructor from being called by Dictionary deserializer
  DSharpPlus/Net/Serialization/SnowflakeArrayAsDictionaryJsonConverter.cs
Labels: bug, core

#471 Add lavalink soundcloud search support.
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkSearchType.cs
  DSharpPlus.Test/TestBotLavaCommands.cs
Labels: lavalink, new-features

#480 Implemented Lavalink load failed details
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkTrack.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/EventArgs/MessageDeleteEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionAddEventArgs.cs
Labels: enhancement, lavalink

#398 Make extensions disposable
  DSharpPlus/DiscordClient.cs
Labels: core, enhancement

#475 Make PermissionsFor properly support administrator
  DSharpPlus/Entities/DiscordChannel.cs
Labels: core, enhancement

#472 Implemented new DiscordMessage properties
  DSharpPlus/Entities/DiscordApplication.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageActivity.cs
  DSharpPlus/Entities/DiscordMessageApplication.cs
  DSharpPlus/Entities/DiscordMessageReference.cs
  DSharpPlus/Enums/MessageActivityType.cs
  DSharpPlus/Enums/MessageType.cs
Labels: core, new-features

#469 Added DiscordGuild properties for several event args
  DSharpPlus/DiscordClient.cs
  DSharpPlus/EventArgs/ChannelPinsUpdateEventArgs.cs
  DSharpPlus/EventArgs/MessageBulkDeleteEventArgs.cs
  DSharpPlus/EventArgs/MessageDeleteEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionAddEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionRemoveEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionsClearEventArgs.cs
  DSharpPlus/EventArgs/TypingStartEventArgs.cs
Labels: core, enhancement

#482 Added new invite properties
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Entities/DiscordInvite.cs
  DSharpPlus/Enums/TargetUserType.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, new-features

#483 Message reference hotfix
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageReference.cs
Labels: bug, core
