Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-11, with the labels that each got.

#662 Fixed typo in CHANNEL_PINS_UPDATED event
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, core, v4.x

#566 Improve the VoiceNext queue
  DSharpPlus.Test/TestBotVoiceCommands.cs
  DSharpPlus.VoiceNext/DSharpPlus.VoiceNext.csproj
  DSharpPlus.VoiceNext/IVoiceFilter.cs
  DSharpPlus.VoiceNext/RawVoicePacket.cs
  DSharpPlus.VoiceNext/StreamExtensions.cs
  DSharpPlus.VoiceNext/VoiceNextConfiguration.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
  DSharpPlus.VoiceNext/VoiceTransmitSink.cs
  DSharpPlus.VoiceNext/VoiceTransmitStream.cs
Labels: enhancement, v4.x, voicenext

#668 Sanity check Webhook AvatarHash
  DSharpPlus/Entities/DiscordWebhook.cs
Labels: bug, core, v4.x

#669 Adds logging functionality for the webhook client.
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Logging/DefaultLoggerFactory.cs
  DSharpPlus/Logging/DefaultLoggerProvider.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Utilities.cs
Labels: bug, core, enhancement, v4.x

#672 [ci skip] Tweak to Lavalink Article
  docs/articles/audio/lavalink/music_commands.md
Labels: docs, enhancement, lavalink, v4.x

#674 Update Migration Guide for 3.x to 4.x to include the logging changes.
  docs/articles/migration/3x_to_4x.md
Labels: docs, enhancement, v4.x

#673 Add Intents to Documentation
  docs/articles/beyond_basics/intents.md
  docs/articles/migration/3x_to_4x.md
  docs/articles/toc.yml
  docs/images/Intents.png
Labels: docs, enhancement, v4.x

#675 [ci-skip] Fixed typos in docs on first bot and hosting
  docs/articles/basics/first_bot.md
  docs/articles/hosting.md
Labels: docs, enhancement, v4.x

#678 Added handling for 5xx responses from Discord
  DSharpPlus/Net/RestClient.cs
Labels: bug, core, v4.x

#680 Feature: Add member object to message events + better intent cache handling
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/DiscordIntents.cs
Labels: core, enhancement, v4.x

#685 Add Missing voice state properties
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/DiscordVoiceState.cs
Labels: core, new-features, v4.x

#689 Implementation of Discord Stickers
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageSticker.cs
Labels: core, new-features, on-hold, v4.x

#690 Add Edit Allowed Mentions in Modify Message
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Net/Abstractions/RestChannelPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, enhancement, v4.x

#691 Add Missing Property for Discord Emoji
  DSharpPlus/Entities/DiscordEmoji.cs
Labels: core, new-features, v4.x

#687 Fix Reconnect Bug when Disallowed/Malformed Intents are provided
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
Labels: bug, core, v4.x
