Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-08, with the labels that each got.

#608 Add shard concurrency + massive DiscordShardedClient rework
  DSharpPlus/BaseDiscordClient.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/DiscordShardedClient.cs
  DSharpPlus/Net/Abstractions/GatewayInfo.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Net/SessionBucket.cs
  DSharpPlus/Net/WebSocket/SocketLock.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
  DSharpPlus/Utilities.cs
Labels: big-change, core, v4.x

#594 Fix error with trailing escape char
  DSharpPlus.CommandsNext/CommandsNextUtilities.cs
Labels: bug, commandsnext, v4.x

#619 Initial Gateway Intent Support
  DSharpPlus.CommandsNext/ExtensionMethods.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/DiscordIntents.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Net/Abstractions/GatewayIdentifyResume.cs
  DSharpPlus/Utilities.cs
Labels: big-change, core, v4.x

#624 Add exception handling for 500 status codes.
  DSharpPlus/Exceptions/ServerErrorException.cs
  DSharpPlus/Net/RestClient.cs
Labels: bug, core, v4.x

#605 Logging overhaul
  DSharpPlus.CommandsNext/CommandsNextEvents.cs
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Entities/CommandResult.cs
  DSharpPlus.CommandsNext/ExtensionMethods.cs
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/InteractivityEvents.cs
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus.Lavalink/EventArgs/TrackEventArgs.cs
  DSharpPlus.Lavalink/LavalinkEvents.cs
  DSharpPlus.Lavalink/LavalinkExtension.cs
  DSharpPlus.Lavalink/LavalinkGuildConnection.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkRest.cs
  DSharpPlus.Test/Program.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotEvalCommands.cs
  DSharpPlus.Test/TestBotLavaCommands.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus.VoiceNext/VoiceNextEvents.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
  DSharpPlus.targets
  DSharpPlus/AsyncEvent.cs
  DSharpPlus/BaseDiscordClient.cs
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/DebugLogger.cs
  DSharpPlus/DiscordClient.cs
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/DiscordShardedClient.cs
  DSharpPlus/Entities/DiscordAuditLogObjects.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Enums/LogLevel.cs
  DSharpPlus/EventArgs/ChannelPinsUpdateEventArgs.cs
  DSharpPlus/EventArgs/ChannelUpdateEventArgs.cs
  DSharpPlus/EventArgs/GuildEmojisUpdateEventArgs.cs
  DSharpPlus/EventArgs/GuildMemberUpdateEventArgs.cs
  DSharpPlus/EventArgs/GuildRoleUpdateEventArgs.cs
  DSharpPlus/EventArgs/MessageBulkDeleteEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionAddEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionRemoveEventArgs.cs
  DSharpPlus/EventArgs/MessageReactionsClearEventArgs.cs
  DSharpPlus/EventArgs/VoiceServerUpdateEventArgs.cs
  DSharpPlus/EventArgs/VoiceStateUpdateEventArgs.cs
  DSharpPlus/Logging/CompositeDefaultLogger.cs
  DSharpPlus/Logging/DefaultLogger.cs
  DSharpPlus/Logging/DefaultLoggerFactory.cs
  DSharpPlus/Logging/DefaultLoggerProvider.cs
  DSharpPlus/Logging/LoggerEvents.cs
  DSharpPlus/Logging/ShardedLoggerFactory.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Utilities.cs
Labels: big-change, core, on-hold, v4.x

#622 Lavalink Additions and Fixes
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus.Lavalink/Entities/LavalinkRouteStatus.cs
  DSharpPlus.Lavalink/Entities/LavalinkUpdates.cs
  DSharpPlus.Lavalink/Enums/LavalinkRoutePlannerType.cs
  DSharpPlus.Lavalink/Enums/LavalinkSearchType.cs
  DSharpPlus.Lavalink/LavalinkConfiguration.cs
  DSharpPlus.Lavalink/LavalinkExtension.cs
  DSharpPlus.Lavalink/LavalinkGuildConnection.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkRestClient.cs
  DSharpPlus/Entities/DiscordVoiceRegion.cs
  DSharpPlus/Net/ConnectionEndpoint.cs
Labels: lavalink, new-features, v4.x

#484 Fix garbled audio data and UDP ping in VNext
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
Labels: bug, on-hold, voicenext
