Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-04, with the labels that each got.

#551 Fix for client not reconnecting when idlesince is set.
  DSharpPlus/DiscordClient.cs
  DSharpPlus/Utilities.cs
Labels: bug, core, v4.x

#552 Support for UserFlags.
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordInvite.cs
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Enums/MessageActivityType.cs
  DSharpPlus/Enums/MessageFlags.cs
  DSharpPlus/Enums/MessageType.cs
  DSharpPlus/Enums/SystemChannelFlags.cs
  DSharpPlus/Enums/TargetUserType.cs
  DSharpPlus/Enums/UserFlags.cs
Labels: core, enhancement, v4.x

#553 Fixes TrackExceptionEvent not firing.
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Net/Abstractions/TransportUser.cs
Labels: bug, lavalink, v4.x

#556 Added public flag support
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Enums/UserFlags.cs
  DSharpPlus/Net/Abstractions/TransportUser.cs
Labels: core, new-features, v4.x

#558 Fix for NullReference if no connection was established #554
  DSharpPlus/DiscordClient.cs
Labels: bug, core, v4.x
