Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-10, with the labels that each got.

#643 Fix Null User Properties When Requesting Guild Members
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#644 Fix User Instance Not Being Found in the MessageReactionAdded event.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/DiscordVoiceState.cs
  DSharpPlus/EventArgs/MessageReactionAddEventArgs.cs
Labels: bug, core, v4.x

#645 Fix for Inaccurate Webhook Authors in Messages.
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core, v4.x

#642 Fixes Exceptions Received in VoiceNext Voice Receive
  DSharpPlus.VoiceNext/EventArgs/VoiceReceiveEventArgs.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
Labels: bug, v4.x, voicenext

#646 Add Member Support for Typing Start Event.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/EventArgs/TypingStartEventArgs.cs
Labels: core, enhancement, v4.x

#647 Use owner json field in DiscordGuild
  DSharpPlus/Entities/DiscordGuild.cs
Labels: core, enhancement, v4.x

#649 Interactivity reorganization and improvement.
  DSharpPlus.Interactivity/Concurrency/ConcurrentHashSet.cs
  DSharpPlus.Interactivity/Concurrency/PlatformHelper.cs
  DSharpPlus.Interactivity/DSharpPlus.Interactivity.csproj
  DSharpPlus.Interactivity/Enums/PaginationBehaviour.cs
  DSharpPlus.Interactivity/Enums/PaginationDeletion.cs
  DSharpPlus.Interactivity/Enums/PollBehaviour.cs
  DSharpPlus.Interactivity/Enums/SplitType.cs
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/EventHandling/Requests/CollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/IPaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PollRequest.cs
  DSharpPlus.Interactivity/Extensions.cs
  DSharpPlus.Interactivity/Extensions/ChannelExtensions.cs
  DSharpPlus.Interactivity/Extensions/ClientExtensions.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityConfiguration.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Interactivity/InteractivityResult.cs
Labels: enhancement, interactivity, v4.x

#652 Adding Missing Guild Widget Methods (#650)
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordWidget.cs
  DSharpPlus/Entities/DiscordWidgetMember.cs
  DSharpPlus/Entities/DiscordWidgetSettings.cs
  DSharpPlus/Net/Abstractions/RestGuildPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Endpoints.cs
Labels: core, new-features, v4.x

#653 Add and improve extension methods.
  DSharpPlus.CommandsNext/ExtensionMethods.cs
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus.VoiceNext/DiscordClientExtensions.cs
Labels: commandsnext, enhancement, interactivity, lavalink, v4.x

#654 Add Competing to ActivityType
  DSharpPlus/Entities/DiscordActivity.cs
Labels: core, new-features, v4.x

#655 Fixed TestBot after Interactivity changes
  DSharpPlus.Test/TestBot.cs
Labels: bug, interactivity, v4.x

#658 Feature: X-Ratelimit-Bucket Support
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Logging/LoggerEvents.cs
  DSharpPlus/Net/BaseRestRequest.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/MultipartWebRequest.cs
  DSharpPlus/Net/RateLimitBucket.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Net/RestRequest.cs
Labels: core, enhancement, v4.x
