Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-06, with the labels that each got.

#590 Fix connect event always firing when trying to connect.
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: bug, core, v4.x

#589 Feature: Implement X-Ratelimit-Reset-After
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/DiscordWebhookClient.cs
  DSharpPlus/Entities/DiscordEmbedBuilder.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RateLimitBucket.cs
  DSharpPlus/Net/RestClient.cs
Labels: core, new-features, v4.x

#588 Added .Auto to ImageFormat to enhance GetAvatarUrl
  DSharpPlus/Entities/DiscordApplication.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/ImageTool.cs
Labels: core, new-features, v4.x

#593 fixed spelling from "alises" to "aliases"
  DSharpPlus.CommandsNext/Entities/Command.cs
Labels: docs, v4.x

#592 Fix for Reset-After not handling parsing correctly.
  DSharpPlus/Net/RestClient.cs
Labels: bug, core, v4.x

#599 Fix WS disconnection and disposal issues.
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: bug, core, v4.x

#595 Making the internal LogHandler threadsafe
  DSharpPlus/DebugLogger.cs
Labels: core, enhancement, on-hold, v4.x

#602 Fixed empty mention array
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordMentions.cs
Labels: bug, core, v4.x

#604 Made code work
  docs/articles/interactivity/intro.md
Labels: docs, enhancement, v4.x

#603 [ci skip] Add Lavalink articles to documentation.
  docs/articles/lavalink/implementation.md
  docs/articles/lavalink/intro.md
  docs/articles/lavalink/music_commands.md
Labels: docs, enhancement, v4.x

#606 Fix typo in DiscordMentions ctor passing role mentions into the users list
  DSharpPlus/Entities/DiscordMentions.cs
Labels: bug, core, v4.x
