Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-09, with the labels that each got.

#625 Fix null ref thrown for CollectEventArgs
  DSharpPlus.Interactivity/EventHandling/Requests/CollectRequest.cs
Labels: bug, interactivity, v4.x

#627 Fix typo in DiscordConfiguration XML docs
  DSharpPlus/DiscordConfiguration.cs
Labels: core, docs, enhancement, v4.x

#630 Implements crosspost and follow to news channels.
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordFollowedChannel.cs
  DSharpPlus/Enums/MessageFlags.cs
  DSharpPlus/Net/Abstractions/FollowedChannelAddPayload.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Endpoints.cs
Labels: core, new-features, v4.x

#632 DiscordShardClient NRE Fix + Minor Code Fixes
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: bug, core, v4.x

#635 Fix ArgumentOfRangeException with Discord message intents.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordMessage.cs
Labels: bug, core, v4.x

#637 Implement HTTP Handling for the DiscordShardedClient
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Logging/LoggerEvents.cs
Labels: bug, core, v4.x

#639 Fixes cnext injection on inherited properties.
  DSharpPlus.CommandsNext/CommandsNextUtilities.cs
Labels: commandsnext, enhancement, v4.x
