Repository DSharpPlus/DSharpPlus, pull requests merged in 2020-12, with the labels that each got.

#693 Fix potential deadlock in VoiceTransmitSink
  DSharpPlus.VoiceNext/VoiceTransmitSink.cs
Labels: bug, v4.x, voicenext

#698 Updated stop time JSON variable to match Lavalink code.
  DSharpPlus.Lavalink/Entities/LavalinkCommands.cs
Labels: bug, lavalink, v4.x

#701 fix: Prevent potential nullrefs on channel update event.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, enhancement, v4.x

#700 fix: Prevent Guild Cache Error Being Called for Current User
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, core, enhancement, v4.x

#702 fix: Fix nullref thrown in RestClient disposal
  DSharpPlus/Net/RestClient.cs
Labels: bug, core, v4.x

#703 fix: Ensure null collections are checked in the guild object.
  DSharpPlus/Entities/DiscordGuild.cs
Labels: bug, core, v4.x

#714 Fixed the channel ID and added a reason option when modifying a webhook
  DSharpPlus/Entities/DiscordWebhook.cs
Labels: bug, core, v4.x

#707 Make DiscordGuild OwnerId public
  DSharpPlus/Entities/DiscordGuild.cs
Labels: core, enhancement, v4.x

#705 Fix stickers
  DSharpPlus/Entities/DiscordMessageSticker.cs
Labels: bug, core, v4.x

#718 Enhancement: Use Streams rather than Strings for Serialization
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkRestClient.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/Program.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/EventArgs/WebSocketMessageEventArgs.cs
  DSharpPlus/Exceptions/BadRequestException.cs
  DSharpPlus/Exceptions/NotFoundException.cs
  DSharpPlus/Exceptions/RateLimitException.cs
  DSharpPlus/Exceptions/RequestSizeException.cs
  DSharpPlus/Exceptions/ServerErrorException.cs
  DSharpPlus/Exceptions/UnauthorizedException.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Net/RestResponse.cs
  DSharpPlus/Net/Serialization/DiscordJson.cs
  DSharpPlus/Net/WebSocket/PayloadDecompressor.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: core, enhancement, v4.x

#684 Update FAQ
  docs/faq.md
Labels: docs, enhancement, v4.x

#724 Fixed dead link going to Naamloos' profile
  docs/index.md
Labels: docs, enhancement, v4.x
