Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-11, with the labels that each got.

#1145 Add Application Flags
  DSharpPlus/Enums/ApplicationFlags.cs
Labels: core, new-features, v4.x

#1137 Add support for `SUPPRESS_JOIN_NOTIFICATION_REPLIES`
  DSharpPlus/Enums/Channel/SystemChannelFlags.cs
Labels: core, new-features, v4.x

#1144 Add helper overloads for slash command responses
  DSharpPlus.SlashCommands/Contexts/BaseContext.cs
Labels: enhancement, v4.x, slash-commands

#1157 Add some properties to AutocompleteContext
  DSharpPlus.SlashCommands/Contexts/AutocompleteContext.cs
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
Labels: enhancement, v4.x, slash-commands

#1159 Add support for creating application or stream invites
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1160 Fix wrong check for boosts on thread creation
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: bug, core, v4.x

#1163 Fix interaction responses not respecting allowed mentions
  DSharpPlus/Entities/Interaction/DiscordInteractionApplicationCommandCallbackData.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: bug, core, v4.x
