Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-05, with the labels that each got.

#869 Added Role Tags object
  DSharpPlus/Entities/Guild/DiscordRole.cs
  DSharpPlus/Entities/Guild/DiscordRoleTags.cs
Labels: core, new-features, v4.x

#873 Fixing weird types in Entities
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: core, enhancement, v4.x

#882 Fix this qualifiers
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/EventHandling/Requests/CollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/MatchRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PollRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotPaginator.cs
  DSharpPlus.VoiceNext/RawVoicePacket.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus/AsyncManualResetEvent.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Optional.cs
  DSharpPlus/Entities/User/DiscordPresence.cs
  DSharpPlus/QueryUriBuilder.cs
Labels: core, enhancement, v4.x

#874 fixed nullable attachment values
  DSharpPlus/Entities/Channel/Message/DiscordAttachment.cs
Labels: core, enhancement, v4.x

#885 fix: Grab guild from cache rather than msg object.
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, core, v4.x

#870 Update Permissions to include newly documented thread permissions
  DSharpPlus/Enums/Permission.cs
Labels: core, new-features, on-hold, v4.x

#887 Update UserFlags to include Discord Certified Moderator
  DSharpPlus/Enums/User/UserFlags.cs
Labels: core, new-features, v4.x

#896 fix: Lavalink failed connection issues
  DSharpPlus.Lavalink/LavalinkConfiguration.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
Labels: bug, lavalink, v4.x

#888 Implement video quality mode
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Enums/Channel/VideoQualityMode.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Models/ChannelEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#892 Add extension methods on CommandsNextExtension dictionaries
  DSharpPlus.CommandsNext/ExtensionMethods.cs
Labels: commandsnext, core, enhancement, v4.x

#901 [ci skip] Update BUILDING.md
  BUILDING.md
Labels: docs

#883 Add nsfw_level to guilds
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Enums/Guild/NsfwLevel.cs
Labels: core, new-features, v4.x

#906 Fix quality mode errors
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Enums/Channel/VideoQualityMode.cs
Labels: bug, core, v4.x
