Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-01, with the labels that each got.

#695 Adds a Message Builder
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/EventArgs/CommandContext.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/ADumbFile.txt
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.Test/TestBotDynamicCommands.cs
  DSharpPlus.Test/TestBotEvalCommands.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
Labels: core, enhancement, v4.x

#727 Added ConfigureAwait statements where needed
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkRestClient.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.Test/TestBotLavaCommands.cs
  DSharpPlus.Test/TestBotPaginator.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus.VoiceNext/VoiceTransmitSink.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
Labels: enhancement, v4.x

#726 [ci skip] Document message builder
  docs/articles/beyond_basics/messagebuilder.md
  docs/articles/migration/3x_to_4x.md
  docs/articles/toc.yml
Labels: docs, enhancement, v4.x

#730 Update Documentation for Intents on Events
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
Labels: docs, enhancement, v4.x

#704 Add Inline Replies in response to #676
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/Reply.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordMentions.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
  DSharpPlus/Entities/DiscordMessageReference.cs
  DSharpPlus/Entities/Mentions.cs
  DSharpPlus/Enums/MessageType.cs
  DSharpPlus/Net/Abstractions/RestChannelPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, new-features, v4.x

#734 Blocking NRE - Add null check for referenced message
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#733 Fix bug when u pass a mention in with a reply
  DSharpPlus.Test/Reply.cs
  DSharpPlus/Entities/DiscordMentions.cs
Labels: bug, core, v4.x

#732 Add pending? property to DiscordMember
  DSharpPlus/Entities/DiscordMember.cs
  DSharpPlus/Net/Abstractions/TransportMember.cs
Labels: core, new-features, v4.x

#735 fix: Ensure disposed stream is not used for further deserialization
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/RestClient.cs
Labels: bug, core, enhancement, v4.x

#737 Updated documentation to add inline replies.
  docs/articles/beyond_basics/messagebuilder.md
Labels: docs, v4.x

#736 Cleanup Internal CreateMessage Methods
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/DiscordChannel.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, enhancement

#742 [ci skip] Fix grammar and typos in the message builder article
  docs/articles/beyond_basics/messagebuilder.md
Labels: docs, enhancement, v4.x

#745 Fix: Properly reset stream index and length during text WS message
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: bug, core, v4.x

#746 Expose the 5,860 emoji names
  DSharpPlus/Entities/DiscordEmoji.cs
Labels: core, enhancement, v4.x

#747 Create pre-built method to make spoilered text
  DSharpPlus/Formatter.cs
Labels: core, enhancement, v4.x
