Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-04, with the labels that each got.

#812 Add welcome screen endpoints
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordGuildWelcomeScreen.cs
  DSharpPlus/Entities/Guild/DiscordGuildWelcomeScreenChannel.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Models/WelcomeScreenEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, new-features, v4.x

#813 Add missing fields on channels
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/DiscordDmChannel.cs
Labels: core, enhancement, new-features, v4.x

#810 Implement slash command endpoints
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionApplicationCommandCallbackData.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
  DSharpPlus/Enums/InteractionResponseType.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, new-features, v4.x

#816 Add new message types
  DSharpPlus/Enums/Message/MessageType.cs
Labels: core, new-features, v4.x

#814 [ci skip] Remove file name example from message builder article
  docs/articles/beyond_basics/messagebuilder.md
Labels: core, docs, enhancement, v4.x

#817 Add ability to make followup message ephemeral
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Interaction/DiscordFollowupMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Enums/Message/MessageFlags.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, enhancement, v4.x

#822 Add limits on application commands name and description
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
Labels: core, enhancement, v4.x

#821 Final 4.0 RC3 fixes
  DSharpPlus.CommandsNext/EventArgs/CommandContext.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: bug, core, enhancement, lavalink, v4.x

#826 fix: Try to cache DM channels during REST.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, enhancement, v4.x

#828 Fix replies erroring out for invalid Ids
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
Labels: bug, core, v4.x

#827 Fix race condition: reaction removal (interactivity)
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
Labels: bug, interactivity, v4.x

#829 Make RespondAsync produce a non-mentioning reply.
  DSharpPlus.CommandsNext/EventArgs/CommandContext.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMentions.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageReference.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: core, new-features, v4.x

#834 fix: Ensure correct shard id when manually sharding.
  DSharpPlus/Clients/DiscordShardedClient.cs
Labels: bug, core, v4.x

#837 Fix inline replies inconsistently throwing Bad Request: 400
  DSharpPlus/Entities/Channel/Message/DiscordMessageReference.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v4.x

#843 fix: Update dependencies
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus/DSharpPlus.csproj
Labels: core, enhancement, v4.x

#844 Fix Lavalink URLs
  docs/articles/audio/lavalink/setup.md
Labels: docs, lavalink

#845 Fixed typo in TryFromName method in DiscordEmoji.cs
  DSharpPlus/Entities/Emoji/DiscordEmoji.cs
Labels: core, enhancement, v4.x

#847 Updates from v5 branch
  DSharpPlus/Entities/Emoji/DiscordEmoji.cs
  docs/articles/audio/lavalink/setup.md
Labels: core, enhancement, lavalink, v4.x

#853 Fix interaction data option value conversion
  DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
Labels: bug, core, v4.x

#854 [ci skip] Update contributing guidelines
  CONTRIBUTING.md
Labels: core, enhancement

#856 [ci skip] Feature/4.0 updates
  CONTRIBUTING.md
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/Entities/Channel/Message/DiscordMessageReference.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  README.md
Labels: v5.x

#857 fix(HasPermission): Always return true if permission contains admin.
  DSharpPlus/Enums/Permission.cs
Labels: bug, core, v4.x

#863 meta: bump versions [ci skip]
  DSharpPlus.targets
  appveyor.yml
Labels: v4.x

#849 Updates permissions to include Use Slash Commands
  DSharpPlus/Enums/Permission.cs
Labels: core, new-features, v4.x

#851 Invite reminder and system message flags
  DSharpPlus/Enums/Channel/SystemChannelFlags.cs
  DSharpPlus/Enums/Message/MessageType.cs
Labels: core, new-features, v4.x

#850 Nsfw guilds
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: core, new-features, v4.x

#859 Implement Stage Channels
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.VoiceNext/DiscordClientExtensions.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
  DSharpPlus/Enums/Channel/ChannelType.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, new-features, v4.x

#864 Match animated emojis
  DSharpPlus/Utilities.cs
Labels: core, enhancement, v4.x

#862 Fix overwrite builder nullrefs
  DSharpPlus/Entities/Channel/Overwrite/DiscordOverwriteBuilder.cs
Labels: bug, core, enhancement, v4.x

#860 Add rtc region on voice channels
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Models/ChannelEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#852 Update permissions to include Request to Speak
  DSharpPlus/Enums/Permission.cs
Labels: core, new-features, v4.x
