Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-12, with the labels that each got.

#1151 Fix null ref when creating DMs
  DSharpPlus.Test/DMTest.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
Labels: bug, enhancement, core, v4.x

#1115 Fix PresenceEvent using new activity on old presence
  DSharpPlus/Entities/User/DiscordActivity.cs
  DSharpPlus/Entities/User/DiscordPresence.cs
Labels: bug, core, v4.x

#1156 Add support to paginate as EditOriginalResponse
  DSharpPlus.Interactivity/Extensions/InteractionExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: enhancement, interactivity, v4.x, slash-commands

#1167 `TimeSpan?` support in slash commands
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
  DSharpPlus.Test/SlashCommandsTimeSpanConverterTest.cs
Labels: enhancement, new-features, v4.x, slash-commands

#1165 Support for scheduled events
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/GuildEventTest.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/DiscordIntents.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/ScheduledEvents/DiscordScheduledGuildEvent.cs
  DSharpPlus/Entities/Guild/ScheduledEvents/DiscordScheduledGuildEventMetadata.cs
  DSharpPlus/Entities/Guild/ScheduledEvents/ScheduledGuildEventPrivacyLevel.cs
  DSharpPlus/Entities/Guild/ScheduledEvents/ScheduledGuildEventStatus.cs
  DSharpPlus/Entities/Guild/ScheduledEvents/ScheduledGuildEventType.cs
  DSharpPlus/Enums/Permission.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventCompletedEventArgs.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventCreateEventArgs.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventDeleteEventArgs.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventUpdateEventArgs.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventUserAddEventArgs.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventUserRemoveEventArgs.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Models/ScheduledGuildEventEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: enhancement, tasks, core, new-features, v4.x

#1164 Support for native mutes
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Enums/Permission.cs
  DSharpPlus/EventArgs/Guild/Member/GuildMemberUpdateEventArgs.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Abstractions/Transport/TransportMember.cs
  DSharpPlus/Net/Models/MemberEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, new-features, v4.x
