Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-07, with the labels that each got.

#970 Fix guild shard formula
  DSharpPlus/Utilities.cs
Labels: bug, core, v4.x

#962 Support for 4096 character embed descriptions
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedBuilder.cs
Labels: core, enhancement, v4.x

#959 [ci skip] Fix button examples
  docs/articles/advanced_topics/buttons.md
Labels: bug, docs, v4.x

#963 Fix SelectComponent ctor not setting component type
  DSharpPlus.Test/SelectTests.cs
  DSharpPlus/Entities/Interaction/Components/DiscordSelectComponent.cs
Labels: bug, core, v4.x

#973 Fix user cache not updating on interaction created
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Interaction/Components/DiscordSelectComponent.cs
Labels: bug, core, v4.x

#967 Remove modify embed suppression endpoint
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, enhancement, v4.x

#971 Fix EmojiUpdate passing the same collection
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#968 fix emoji == and Equals
  DSharpPlus/Entities/Emoji/DiscordEmoji.cs
Labels: bug, core, v4.x

#978 Fix Docs
  DSharpPlus/Entities/Guild/DiscordGuildPreview.cs
Labels: core, enhancement, v4.x

#987 Fixed DM Channels being null on API requests
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v4.x

#992 Fix arbitrary sequence number in GW payloads
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, enhancement, v4.x

#969 Fix VNext choking the ThreadPool
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus/Net/Udp/DspUdpClient.cs
Labels: bug, v4.x, voicenext

#983 Add component-based interactivity
  DSharpPlus.Interactivity/Enums/ButtonPaginationBehavior.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentPaginator.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/PaginationButtons.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ButtonPaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentCollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentMatchRequest.cs
  DSharpPlus.Interactivity/EventHandling/IPaginator.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Requests/IPaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityConfiguration.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Test/Buttons.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotPaginator.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Interaction/Components/DiscordButtonComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordSelectComponent.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: interactivity, new-features, v4.x

#960 Add Guild-Sticker support
  DSharpPlus.Test/StickerTestCommands.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageSticker.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageStickerPack.cs
  DSharpPlus/Entities/DiscordAuditLogObjects.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Enums/Permission.cs
  DSharpPlus/EventArgs/Guild/GuildStickersUpdateEventArgs.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestStickerPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, new-features, v4.x

#1001 Add ignoreDms for require permission attributes
  DSharpPlus.CommandsNext/Attributes/RequireBotPermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequirePermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequireUserPermissionsAttribute.cs
Labels: commandsnext, enhancement, v4.x

#1002 Add ClearComponents method
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordFollowupMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
Labels: core, new-features, v4.x

#1004 Add DeleteOverwriteAsync methods to DiscordChannel
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: core, enhancement, v4.x

#997 Add support for new application command option types
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOptionChoice.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandOptionType.cs
Labels: new-features, on-hold, v4.x

#1011 Fix interactivity overloads and documentation
  DSharpPlus.Interactivity/Extensions/ChannelExtensions.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: enhancement, interactivity, v4.x
