Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-06, with the labels that each got.

#907 Add Search to Guild
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: core, new-features, v4.x

#908 Fix WaitForButton extension methodusing wrong overload
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
Labels: bug, interactivity, v4.x

#911 [ci skip] remove archived example bot
  README.md
Labels: docs, enhancement

#912 Breaking changes time!~ (WithComponents -> AddComponents)
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Interaction/Components/DiscordActionRowComponent.cs
  DSharpPlus/Entities/Interaction/DiscordFollowupMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
Labels: core, enhancement, v4.x

#914 Fix broken buttons
  DSharpPlus/Entities/Interaction/Components/DiscordActionRowComponent.cs
Labels: bug, core, v4.x

#915 Fix webhook builder buttons
  DSharpPlus.Test/Buttons.cs
  DSharpPlus.Test/RoleMenuCommand.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
Labels: core, enhancement, v4.x

#913 Add support for guild-specific avatars
  DSharpPlus.Test/AvatarCommands.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Net/Abstractions/Transport/TransportMember.cs
Labels: bug, core, new-features, v4.x

#916 [Code Clean-up] Add Missing XML Doc Param and deal with warnings in code
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: docs, enhancement, interactivity, v4.x

#920 [ci skip] Fix broken code in buttons article
  docs/articles/advanced_topics/buttons.md
Labels: core, docs, enhancement, v4.x

#927 Fix member search endpoint
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v4.x

#926 Fix Spelling in NsfwLevel.cs
  DSharpPlus/Enums/Guild/NsfwLevel.cs
Labels: core, enhancement, v4.x

#923 Fix minor typo description on DiscordComponent
  DSharpPlus/Entities/Interaction/Components/DiscordComponent.cs
Labels: core, enhancement, v4.x

#924 Add type converter for DiscordComponent
  DSharpPlus/Entities/Interaction/Components/DiscordComponent.cs
  DSharpPlus/Net/Serialization/DiscordComponentJsonConverter.cs
Labels: bug, core, v4.x

#925 Improve DiscordMember converter
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
Labels: commandsnext, enhancement, v4.x

#928 Minor Typo Fixes in comments
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/DiscordDmChannel.cs
  DSharpPlus/Entities/Color/DiscordColor.Colors.cs
  DSharpPlus/Entities/DiscordAuditLogObjects.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Enums/Permission.cs
  DSharpPlus/Net/Abstractions/Transport/TransportActivity.cs
  DSharpPlus/Utilities.cs
Labels: core, enhancement, v4.x

#930 Minor Typo in comment and Exception message
  DSharpPlus.CommandsNext/CommandsNextUtilities.cs
  DSharpPlus.Interactivity/Enums/InteractionResponseBehavior.cs
Labels: commandsnext, enhancement, interactivity, v4.x

#931 Add GetGuildBan support
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#932 Fix inline replies breaking mentions
  DSharpPlus/Entities/Channel/Message/DiscordMentions.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v4.x

#937 Fix Typo in InteractionResponseType
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Test/Buttons.cs
  DSharpPlus/Enums/InteractionResponseType.cs
  docs/articles/advanced_topics/buttons.md
Labels: core, enhancement, v4.x

#943 Small cleanup to DiscordMentions.cs and RepliedUser
  DSharpPlus/Entities/Channel/Message/DiscordMentions.cs
Labels: bug, core, v4.x

#940 Add TimeStamp support.
  DSharpPlus/Enums/TimestampFormat.cs
  DSharpPlus/Formatter.cs
Labels: core, new-features, v4.x

#945 Update CustomMemberIndexer plugin
  docs/dsplus/plugins/HSNXT.DocFx.CustomMemberIndexer.dll
Labels: bug, docs, v4.x

#946 Add DateTime overload to Formatter.Timestamp
  DSharpPlus/Formatter.cs
Labels: core, enhancement, v4.x

#921 Add support for multi embeds
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/MultiEmbedTest.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#949 Fix component-related bugs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/Buttons.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Interaction/Components/DiscordButtonComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordSelectComponent.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: bug, core, v4.x

#922 Add limits on slash command entities
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOptionChoice.cs
  DSharpPlus/Utilities.cs
Labels: core, enhancement, v4.x

#952 [ci skip] Add Oracle Cloud Free Tier to hosting
  docs/articles/hosting.md
Labels: docs

#954 Add support for slash command permissions
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Interaction/Permissions/DiscordApplicationCommandPermission.cs
  DSharpPlus/Entities/Interaction/Permissions/DiscordGuildApplicationCommandPermissions.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandOptionType.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandPermissionType.cs
  DSharpPlus/Enums/Interaction/ButtonStyle.cs
  DSharpPlus/Enums/Interaction/ComponentType.cs
  DSharpPlus/Enums/Interaction/InteractionResponseType.cs
  DSharpPlus/Enums/Interaction/InteractionType.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#953 Add support for sending files while editing messages
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#917 Add permissions property to DiscordMember
  DSharpPlus/Entities/Guild/DiscordMember.cs
Labels: core, enhancement, v4.x

#957 Better version of #956
  DSharpPlus/Entities/Interaction/Components/DiscordActionRowComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordLinkButtonComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordSelectComponent.cs
Labels: bug, core, v4.x

#955 Add missing fields to channel position modify
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
Labels: core, new-features, v4.x

#961 [ci skip] Fix spelling in readme
  README.md
Labels: docs, v4.x
