Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-02, with the labels that each got.

#752 Add pending property to GuildMemberUpdated
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/EventArgs/GuildMemberUpdateEventArgs.cs
Labels: core, new-features, v4.x

#748 Fix: Ensure user is cached before GuildMemberRemoved
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#750 Feature: API V8 Support
  DSharpPlus.CommandsNext/ExtensionMethods.cs
  DSharpPlus.Lavalink/DiscordClientExtensions.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Lavalink/LavalinkRestClient.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/Program.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordMessageSticker.cs
  DSharpPlus/Entities/DiscordPresence.cs
  DSharpPlus/EventArgs/DMChannelCreateEventArgs.cs
  DSharpPlus/EventArgs/WebSocketMessageEventArgs.cs
  DSharpPlus/Exceptions/BadRequestException.cs
  DSharpPlus/Exceptions/NotFoundException.cs
  DSharpPlus/Exceptions/RateLimitException.cs
  DSharpPlus/Exceptions/RequestSizeException.cs
  DSharpPlus/Exceptions/ServerErrorException.cs
  DSharpPlus/Exceptions/UnauthorizedException.cs
  DSharpPlus/Net/Abstractions/GatewayIdentifyResume.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Endpoints.cs
  DSharpPlus/Net/RestClient.cs
  DSharpPlus/Net/RestResponse.cs
  DSharpPlus/Net/Serialization/DiscordJson.cs
  DSharpPlus/Net/WebSocket/PayloadDecompressor.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: big-change, core, enhancement, v4.x

#753 fix(util): intent method params should not be nullable.
  DSharpPlus/Utilities.cs
Labels: core, enhancement, v4.x

#756 fix(message): Ensure skeleton channel is created if channel is not found in cache.
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/EventArgs/MessageCreateEventArgs.cs
  DSharpPlus/EventArgs/MessageUpdateEventArgs.cs
Labels: bug, core, v4.x

#758 Add missing properties on DiscordInviteGuild
  DSharpPlus/Entities/DiscordInviteGuild.cs
Labels: core, enhancement, v4.x

#760 fix(core): Don't add member objects to user cache.
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#762 Implement Welcome Screen Object
  DSharpPlus/Entities/DiscordGuildWelcomeScreen.cs
  DSharpPlus/Entities/DiscordGuildWelcomeScreenChannel.cs
  DSharpPlus/Entities/DiscordInviteGuild.cs
Labels: core, new-features, v4.x

#763 Implement Membership Screening
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/DiscordGuild.cs
  DSharpPlus/Entities/DiscordGuildMembershipScreening.cs
  DSharpPlus/Entities/DiscordGuildMembershipScreeningField.cs
  DSharpPlus/Enums/MembershipScreeningFieldType.cs
  DSharpPlus/Net/Abstractions/RestGuildPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/Endpoints.cs
  DSharpPlus/Net/Models/MembershipScreeningEditModel.cs
Labels: core, new-features, v4.x

#765 Update DiscordClient to return a DiscordDmChannel if appropriate
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, core, v4.x

#764 Don't add the reactions when the paginator has one page
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Requests/IPaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/Requests/PaginationRequest.cs
Labels: enhancement, interactivity, v4.x

#772 Fix null reference on module startup
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
Labels: bug, commandsnext, v4.x

#773 [ci skip] Fix documentation for ChannelEditModel.UserLimit
  DSharpPlus/Net/Models/ChannelEditModel.cs
Labels: core, enhancement, v4.x

#775 Fix File Lock in MessageBuilder Option 2
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
  DSharpPlus/Entities/DiscordMessageFile.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Entities/DiscordWebhookBuilder.cs
  DSharpPlus/Net/DiscordApiClient.cs
  DSharpPlus/Net/MultipartWebRequest.cs
Labels: core, enhancement, v4.x

#785 [ci skip] Fixed documentation typos on multiple pages
  docs/articles/basics/bot_account.md
  docs/articles/beyond_basics/intents.md
  docs/articles/hosting.md
  docs/articles/preamble.md
Labels: docs, enhancement, v4.x

#784 Union Message Parsed Mentions with Discord Mention Lists
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordUser.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core, v4.x

#783 Builder Enhancements
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
  DSharpPlus/Entities/DiscordMessageFile.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Entities/DiscordWebhookBuilder.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core, enhancement, new-features, v4.x
