Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-08, with the labels that each got.

#1022 Fix Xml docs for CNext Permissions related attributes
  DSharpPlus.CommandsNext/Attributes/RequireBotPermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequirePermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequireUserPermissionsAttribute.cs
Labels: commandsnext, enhancement, v4.x

#1012 Fix interactivity overloads
  DSharpPlus.Interactivity/Extensions/ChannelExtensions.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: enhancement, interactivity, v4.x

#1007 Integrate Sticker AuditLog objects
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: core, enhancement, v4.x

#1000 Fix interaction channel being null on dms
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
Labels: bug, core, v4.x

#999 Implement GetFollowupMessage & GetWebhookMessage
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Webhook/DiscordWebhook.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1019 Add support for integration events
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/EventArgs/Integration/IntegrationCreateEventArgs.cs
  DSharpPlus/EventArgs/Integration/IntegrationDeleteEventArgs.cs
  DSharpPlus/EventArgs/Integration/IntegrationUpdateEventArgs.cs
Labels: core, new-features, v4.x

#1025 Fix interactivity acking buttons
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
Labels: bug, interactivity, v4.x

#1028 Multi-component interactivity fix
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentCollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentMatchRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Test/InteractivityTest.cs
Labels: enhancement, interactivity, v4.x

#1033 Dropdown article
  DSharpPlus.Interactivity/InteractivityExtension.cs
  docs/articles/advanced_topics/selects.md
  docs/articles/toc.yml
  docs/images/advanced_topics_selects_01.png
  docs/images/advanced_topics_selects_02.png
Labels: core, docs, v4.x

#1006 Context Menu Support!
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionData.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResolvedCollection.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandType.cs
  DSharpPlus/EventArgs/Interaction/ComponentInteractionCreateEventArgs.cs
  DSharpPlus/EventArgs/Interaction/ContextMenuInteractionCreateEventArgs.cs
  DSharpPlus/EventArgs/Interaction/InteractionCreateEventArgs.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1035 Context menu fixes
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOptionChoice.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionData.cs
  DSharpPlus/Entities/Interaction/Permissions/DiscordApplicationCommandPermission.cs
  DSharpPlus/Entities/Interaction/Permissions/DiscordGuildApplicationCommandPermissions.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandType.cs
  DSharpPlus/Enums/Interaction/InteractionType.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, enhancement, core, v4.x

#1040 [Semi Breaking Change] Add predicate overload to WaitForComponent
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, enhancement, interactivity, v4.x

#1039 Add AccessChannels permission to pre-join check
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
Labels: bug, voicenext, v4.x

#1021 Add a Zombied event to clients
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/EventArgs/ZombiedEventArgs.cs
Labels: core, new-features

#1042 Stop DiscordIntegrationAccount inheriting from SnowflakeObject
  DSharpPlus/Entities/Integration/DiscordIntegrationAccount.cs
Labels: bug, core, v4.x

#1045 Expose a Logger for DiscordWebhookClient
  DSharpPlus/Clients/DiscordWebhookClient.cs
Labels: enhancement, core, v4.x

#975 Add support for user banners/banner color
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/User/DiscordUser.cs
  DSharpPlus/Net/Abstractions/Transport/TransportUser.cs
Labels: core, new-features, v4.x

#1049 Changed properties on DiscordChannel return IReadOnlyList
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: enhancement, core, v4.x

#1050 Create method for updating user cache and fix banner caching
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v4.x

#1051 Improve voice state cache behavior.
  DSharpPlus.targets
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v4.x

#1056 [ci skip] Fix typo in toc.yml
  docs/articles/toc.yml
Labels: bug, docs, v4.x
