Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-03, with the labels that each got.

#780 [ci skip] Update of Documentation
  docs/articles/basics/first_bot.md
  docs/articles/beyond_basics/intents.md
  docs/articles/migration/3x_to_4x.md
  docs/faq.md
  docs/index.md
Labels: core, docs, enhancement, v4.x

#787 Implement webhook message edit and delete endpoints
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Entities/DiscordWebhookBuilder.cs
  DSharpPlus/Net/Abstractions/RestWebhookPayloads.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, new-features, v4.x

#788 Updates the Builders to have a Validate Method
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/DiscordMessage.cs
  DSharpPlus/Entities/DiscordMessageBuilder.cs
  DSharpPlus/Entities/DiscordWebhook.cs
  DSharpPlus/Entities/DiscordWebhookBuilder.cs
  DSharpPlus/Net/DiscordApiClient.cs
Labels: core, enhancement, v4.x

#791 fix(guild): Don't require guild members intent for user cache.
  DSharpPlus/Entities/DiscordGuild.cs
Labels: bug, core, v4.x

#793 feature: Add new message types.
  DSharpPlus/Enums/MessageType.cs
Labels: core, enhancement, new-features, v4.x

#794 Add new emoji from Twemoji 13
  DSharpPlus/Entities/DiscordEmoji.EmojiUtils.cs
Labels: bug, core, enhancement, v4.x

#795 Fix Interactivity Event Timeouts
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
Labels: bug, enhancement, interactivity, v4.x

#796 Adds missing ImageUrl copy in the copy ctor
  DSharpPlus/Entities/DiscordEmbedBuilder.cs
Labels: bug, core, v4.x

#797 Interactivity: Single Line Pages
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, core, v4.x

#798 Update Formatter.cs
  DSharpPlus/Formatter.cs
Labels: core, enhancement, v4.x

#800 fix(apiclient): Handle reply when message is deleted.
  DSharpPlus/Net/DiscordApiClient.cs
Labels: bug, core, v4.x

#803 Fix member in interactions
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: core, enhancement, v4.x

#804 Implement MessageInteraction
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageInteraction.cs
Labels: core, new-features, v4.x

#805 Fix permissions in audit logs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: bug, core, v4.x
