Repository DSharpPlus/DSharpPlus, pull requests merged in 2021-09, with the labels that each got.

#1060 Remove application command events
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
Labels: enhancement, core, v4.x

#1063 Add context menu message type
  DSharpPlus/Enums/Message/MessageType.cs
Labels: enhancement, core, v4.x

#1066 Fix VNext KeepAlive token causing null ref
  DSharpPlus.Test/VoiceNextTest.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
Labels: bug, voicenext, v4.x

#1068 Add version property on ApplicationCommand
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
Labels: core, new-features, v4.x

#1061 Fix potential nullref on stage instances
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, core, v4.x

#1069 Fix members not being cached on voice state update and interactions
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
Labels: bug, enhancement, core, v4.x

#1064 Add missing ConfigureAwaits
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentPaginator.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ButtonPaginationRequest.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/InteractionPaginationRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, v4.x

#1071 Add missing .this
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: enhancement, core, v4.x

#1027 Guild create and modify
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Models/GuildEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1052 Support for non-uids in interactivity
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentCollectRequest.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/Requests/ComponentMatchRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Test/InteractivityTest.cs
Labels: bug, enhancement, interactivity, v4.x

#1062 Change positional logging params to named logging params
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Lavalink/LavalinkNodeConnection.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.VoiceNext/VoiceNextConnection.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: enhancement, commandsnext, voicenext, interactivity, core, lavalink, v4.x

#1067 Fix button pagination overloads and timeout
  DSharpPlus.Interactivity/Extensions/ChannelExtensions.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, enhancement, interactivity, v4.x

#1070 Fix specifying a null embed throwing an exception
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
Labels: bug, core, v4.x

#1074 Fix WrapAround breaking left pagination buttons
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, interactivity, v4.x

#1077 Change HostPls to Xenyth
  docs/articles/hosting.md
Labels: docs

#1081 Fixed getter for DiscordMessage.Channel
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
Labels: bug, core, v4.x

#1072 Add missing channel properties
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageActivity.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Models/ChannelEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1075 Add support for channel types in slash commands
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
Labels: core, new-features, v4.x

#1076 Add support for executing webhooks on threads
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1058 Implement permission changes
  DSharpPlus/Enums/Permission.cs
Labels: enhancement, core, on-hold, v4.x

#1086 Added LavalinkSearchType.Plain
  DSharpPlus.Lavalink/Enums/LavalinkSearchType.cs
  DSharpPlus.Lavalink/LavalinkRestClient.cs
Labels: enhancement, new-features, lavalink, v4.x

#1059 Fix editing messages containing replies in the message builder
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
Labels: bug, enhancement, v4.x

#1087 Optimized and added proper time handling to Formatter.Timestamp.
  DSharpPlus/Formatter.cs
Labels: enhancement, core, v4.x

#1054 Fix reply mention oddities
  DSharpPlus.Test/MentionValidation.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, enhancement, core, big-change, v4.x

#1082 Fixed Channel Property for EventArgs Being Null in Threads/DM's
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannelMember.cs
  DSharpPlus/EventArgs/Message/Reaction/MessageReactionAddEventArgs.cs
  DSharpPlus/EventArgs/Message/Reaction/MessageReactionsClearEventArgs.cs
Labels: bug, core, v4.x

#1043 Interactivity exception consistency
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, interactivity, v4.x

#1091 Add missing methods on the rest client
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: enhancement, core, v4.x

#1088 Added DiscordThreadChannel Entity Converter
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
Labels: enhancement, commandsnext, v4.x

#1093 Fix lavalink search
  DSharpPlus.Lavalink/LavalinkRestClient.cs
Labels: bug, lavalink, v4.x

#1094 Merge IDoEverything.DSharpPlus.SlashCommands into the library as DSharpPlus.SlashCommands
  DSharpPlus.SlashCommands/ApplicationCommandModule.cs
  DSharpPlus.SlashCommands/Attributes/ChannelTypesAttribute.cs
  DSharpPlus.SlashCommands/Attributes/ChoiceAttribute.cs
  DSharpPlus.SlashCommands/Attributes/ChoiceNameAttribute.cs
  DSharpPlus.SlashCommands/Attributes/ChoiceProviderAttribute.cs
  DSharpPlus.SlashCommands/Attributes/ContextMenuAttribute.cs
  DSharpPlus.SlashCommands/Attributes/DontInjectAttribute.cs
  DSharpPlus.SlashCommands/Attributes/OptionAttribute.cs
  DSharpPlus.SlashCommands/Attributes/SlashCommandAttribute.cs
  DSharpPlus.SlashCommands/Attributes/SlashCommandGroupAttribute.cs
  DSharpPlus.SlashCommands/Attributes/SlashModuleLifespanAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequireBotPermissionsAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequireDirectMessageAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequireGuildAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequireOwnerAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequirePermissionsAttribute.cs
  DSharpPlus.SlashCommands/Built-in Checks/SlashRequireUserPermissionsAttribute.cs
  DSharpPlus.SlashCommands/ChoiceProvider.cs
  DSharpPlus.SlashCommands/ContextMenuCheckBaseAttribute.cs
  DSharpPlus.SlashCommands/ContextMenuExecutionChecksFailedException.cs
  DSharpPlus.SlashCommands/Contexts/BaseContext.cs
  DSharpPlus.SlashCommands/Contexts/ContextMenuContext.cs
  DSharpPlus.SlashCommands/Contexts/InteractionContext.cs
  DSharpPlus.SlashCommands/DSharpPlus.SlashCommands.csproj
  DSharpPlus.SlashCommands/EventArgs/ContextMenuErrorEventArgs.cs
  DSharpPlus.SlashCommands/EventArgs/ContextMenuExecutedEventArgs.cs
  DSharpPlus.SlashCommands/EventArgs/SlashCommandErrorEventArgs.cs
  DSharpPlus.SlashCommands/EventArgs/SlashCommandExecutedEventArgs.cs
  DSharpPlus.SlashCommands/ExtensionMethods.cs
  DSharpPlus.SlashCommands/IChoiceProvider.cs
  DSharpPlus.SlashCommands/LICENSE
  DSharpPlus.SlashCommands/README.md
  DSharpPlus.SlashCommands/SlashCheckBaseAttribute.cs
  DSharpPlus.SlashCommands/SlashCommandConfiguration.cs
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
  DSharpPlus.SlashCommands/SlashExecutionChecksFailedException.cs
  DSharpPlus.sln
  DSharpPlus.targets
  DSharpPlus/Properties/AssemblyProperties.cs
Labels: new-features, big-change, v4.x

#1097 Fix WaitForSelect
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, interactivity, v4.x

#1096 Add ephemeral property on attachment
  DSharpPlus/Entities/Channel/Message/DiscordAttachment.cs
Labels: core, new-features, v4.x

#1089 Implement Slash Command AutoComplete
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
  DSharpPlus/Entities/Interaction/Application/DiscordAutoCompleteChoice.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionApplicationCommandCallbackData.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionDataOption.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Enums/Interaction/ApplicationCommandType.cs
  DSharpPlus/Enums/Interaction/InteractionResponseType.cs
  DSharpPlus/Enums/Interaction/InteractionType.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x, slash-commands

#1095 Fix left pagination buttons (again)
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, interactivity, v4.x
