Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-05, with the labels that each got.

#1303 Added RequireReferencedMessageAttribute.
  DSharpPlus.CommandsNext/Attributes/RequireReferencedMessageAttribute.cs
Labels: new-features, v4.x

#1154 add guild member update username property
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/EventArgs/Guild/Member/GuildMemberUpdateEventArgs.cs
Labels: enhancement, core, v4.x

#1309 Revert #1261
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
Labels: commandsnext, v4.x

#1308 Add missing audit log action types and fields
  DSharpPlus/Entities/DiscordAuditLogObjects.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Abstractions/AuditLogAbstractions.cs
Labels: enhancement, core, v4.x

#1120 Fixed NRE in Thread Members Update
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
Labels: bug, core, on-hold, v4.x

#1317 Fix docs typos in DiscordRestClient
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/DiscordDmChannel.cs
  DSharpPlus/Entities/Channel/DiscordFollowedChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  docs/articles/preamble.md
Labels: docs, v4.x

#1320 Implement smart quote handling in CommandsNext (#1268)
  DSharpPlus.CommandsNext/CommandsNextConfiguration.cs
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/CommandsNextUtilities.cs
  DSharpPlus.CommandsNext/Entities/CommandGroup.cs
Labels: enhancement, commandsnext, v4.x
