Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-06, with the labels that each got.

#1149 Text in Voice (TiV) support
  DSharpPlus.Test/VoiceTextTests.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Utilities.cs
Labels: core, new-features, on-hold, big-change, v4.x

#1331 Refactored `DiscordMessage.PopulateMentions` and `DiscordClient.OnMessageUpdateEventAsync`
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
Labels: bug, enhancement, core, v4.x

#1330 Improve XML documentation for DiscordClient.Ready
  DSharpPlus/Clients/DiscordClient.Events.cs
Labels: enhancement, docs, v4.x
