Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-11, with the labels that each got.

#1412 Add AttributeTargets.Method on GuildOnlyAttribute since it's missing
  DSharpPlus.SlashCommands/Attributes/GuildOnlyAttribute.cs
Labels: bug, v4.x, slash-commands

#1404 Adds forum channel type.
  DSharpPlus/Enums/Channel/ChannelType.cs
Labels: core, new-features, v4.x, hacktoberfest-accepted

#1413 Add abstractions for MessageBuilders (IDiscordMessageBuilder)
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/IDiscordMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordFollowupMessageBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Entities/Webhook/DiscordWebhookBuilder.cs
Labels: enhancement, new-features, v4.x
