Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-08, with the labels that each got.

#1363 Fix #1325 - WebhookBuilder Throws Bad Request
  DSharpPlus/Net/Abstractions/Rest/RestWebhookPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v4.x

#1366 Cache threads upon thread creation
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: enhancement, core, v4.x

#1371 categorization for the cnext default help command
  DSharpPlus.CommandsNext/Attributes/CategoryAttribute.cs
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Converters/DefaultHelpFormatter.cs
  DSharpPlus.CommandsNext/Entities/Builders/CommandBuilder.cs
  DSharpPlus.CommandsNext/Entities/Command.cs
Labels: enhancement, commandsnext, v4.x

#1364 Fix memberBefore missing roles in GuildMemberUpdateEventArgs when not…
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: enhancement, core, v4.x

#1375 Ported CommandsNext cooldown attribute to Slash Commands
  DSharpPlus.SlashCommands/Built-in Checks/SlashCooldownAttribute.cs
Labels: enhancement, help wanted, new-features, v4.x, slash-commands
