Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-07, with the labels that each got.

#1337 Fix #1331
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/EventArgs/Message/MessageUpdateEventArgs.cs
Labels: bug, enhancement, core, docs, v4.x

#1339 Slash Command option length support for STRING option types
  DSharpPlus.SlashCommands/Attributes/MaximumLengthAttribute.cs
  DSharpPlus.SlashCommands/Attributes/MinimumLengthAttribute.cs
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
  DSharpPlus.Test/SlashCommandMinMaxLengthTest.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
Labels: enhancement, v4.x, slash-commands

#1341 Fix a small issue where TargetUser can be null in message context men…
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
Labels: bug, v4.x, slash-commands

#1342 Switch tests to NUnit + 1 test case per payload
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus.Test/Serialization/Core/TestPayloadSerialization.cs
Labels: enhancement, core, v5.x

#1343 Use IJsonTypeInfoResolver to ignore Optional<T>
  DSharpPlus.Core/DSharpPlus.Core.csproj
  DSharpPlus.Core/Entities/Optional.cs
  DSharpPlus.Core/JsonConverters/DiscordJsonTypeInfoResolverHelper.cs
  DSharpPlus.Test/Serialization/Core/JsonOptional.cs
  DSharpPlus.Test/Serialization/Core/TestPayloadSerialization.cs
Labels: enhancement, core, v5.x

#1346 Added DiscordConfiguration.LogUnknownEvents
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/DiscordConfiguration.cs
Labels: enhancement, core, v4.x

#1347 Update ReadMe Badges
  README.md
Labels: enhancement, docs

#1348 Make DiscordConfiguration.LogUnknownEvents actually work
  DSharpPlus/DiscordConfiguration.cs
Labels: bug, core, v4.x

#1352 Update emoji database
  DSharpPlus/Entities/Emoji/DiscordEmoji.EmojiUtils.cs
Labels: enhancement, core, v4.x

#1333 Removed most compiler warnings.
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Stage/DiscordStageInstance.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/EventArgs/Guild/ScheduledEvents/ScheduledGuildEventUserRemoveEventArgs.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, docs, v4.x

#1359 Change GuildMemberUpdatedEventArgs to contain before and after DiscordMember objects
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/EventArgs/Guild/Member/GuildMemberUpdateEventArgs.cs
Labels: enhancement, core, v4.x
