Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-03, with the labels that each got.

#1223 Set default value for ephemeral on followup message builder
  DSharpPlus/Entities/Interaction/DiscordFollowupMessageBuilder.cs
Labels: enhancement, core

#1230 Fixed WaitForModalAsync() and added overload
  DSharpPlus.Interactivity/EventHandling/ModalEventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Requests/ModalMatchRequest.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Test/ModalCommand.cs
  DSharpPlus.Test/TestBot.cs
Labels: bug, v4.x, slash-commands

#1235 Cleanup DiscordThreadChannel.cs and fix DiscordThreadChannel.ModifyAsync
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
Labels: bug, core, v4.x

#1236 Cleanup DiscordGuild.cs and add position argument to channel creation methods
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v4.x

#1221 [ci-skip] Switch ci
  .github/workflows/publish_nightly.yml
  .github/workflows/publish_release.yml
  .github/workflows/test_pr.yml
  .gitignore
  .nuget/NuGet.config
  README.md
  appveyor.yml
  oneclick-rebuild.ps1
  rebuild-all.ps1
  rebuild-docs.ps1
  rebuild-lib.ps1
  rebuild-micro.ps1
Labels: big-change

#1224 Adds role ID support to RequireRolesAttribute
  DSharpPlus.CommandsNext/Attributes/RequireRolesAttribute.cs
Labels: enhancement, commandsnext, v4.x

#1216 Fix errors and warnings for DSharpPlus.Test
  .editorconfig
  DSharpPlus.Test/.editorconfig
  DSharpPlus.Test/AvatarCommands.cs
  DSharpPlus.Test/BeeMovie.cs
  DSharpPlus.Test/Buttons.cs
  DSharpPlus.Test/DMTest.cs
  DSharpPlus.Test/DSharpPlus.Test.csproj
  DSharpPlus.Test/GuildEventTest.cs
  DSharpPlus.Test/InteractivityTest.cs
  DSharpPlus.Test/MentionValidation.cs
  DSharpPlus.Test/PaginationTest.cs
  DSharpPlus.Test/Program.cs
  DSharpPlus.Test/Role-IconTest.cs
  DSharpPlus.Test/RoleMenuCommand.cs
  DSharpPlus.Test/SelectTests.cs
  DSharpPlus.Test/SlashCommandMinMaxTest.cs
  DSharpPlus.Test/SlashCommandsTimeSpanConverterTest.cs
  DSharpPlus.Test/StickerTestCommands.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus.Test/TestBotCommands.cs
  DSharpPlus.Test/TestBotDynamicCommands.cs
  DSharpPlus.Test/TestBotEvalCommands.cs
  DSharpPlus.Test/TestBotHelpFormatter.cs
  DSharpPlus.Test/TestBotLavaCommands.cs
  DSharpPlus.Test/TestBotPaginator.cs
  DSharpPlus.Test/TestBotVoiceCommands.cs
  DSharpPlus.Test/VoiceNextTest.cs
Labels: enhancement, v4.x

#1195 Thread timestamps
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannelMetadata.cs
  DSharpPlus/EventArgs/Channel/Thread/ThreadCreateEventArgs.cs
Labels: enhancement, core, v4.x

#1208 Fix `.AddOrUpdate` usage which causes outdated caching
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
Labels: bug, enhancement, core, v4.x

#1243 hotfix: Attempt to fix presence SO
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, enhancement, help wanted, core, v4.x

#1248 Make mentions optional in ApiClient.EditMessageAsync
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v4.x
