Repository DSharpPlus/DSharpPlus, pull requests merged in 2022-01, with the labels that each got.

#1182 Fixed serializing DiscordLinkButtons
  DSharpPlus/Net/Serialization/DiscordComponentJsonConverter.cs
Labels: bug, enhancement, core, v4.x

#1188 Add GetThreadMemberAsync
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: core, new-features, v4.x

#1189 Add PremiumProgressBarEnabled to DiscordGuild.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: core, new-features, v4.x

#1194 Use X-Audit-Log-Header when possible
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v4.x

#1193 Fix DiscordGuild#ModifyAsync
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Optional.cs
  DSharpPlus/Net/Models/GuildEditModel.cs
Labels: bug, core, v4.x
