Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-05, with the labels that each got.

#1554 Add NSFW flag to Slash Commands
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.SlashCommands/Attributes/ContextMenuAttribute.cs
  DSharpPlus.SlashCommands/Attributes/SlashCommandAttribute.cs
  DSharpPlus.SlashCommands/Attributes/SlashCommandGroupAttribute.cs
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, new-features, v4.x, slash-commands

#1556 replace .editorconfig with the one in aki's branch
  .editorconfig
Labels: v5.x

#1557 fix links in articles
  docs/articles/advanced_topics/buttons.md
  docs/articles/advanced_topics/selects.md
  docs/articles/audio/lavalink/music_commands.md
  docs/articles/basics/first_bot.md
  docs/articles/commands/intro.md
Labels: enhancement, docs, v5.x

#1559 fix events blocking the gateway
  DSharpPlus/AsyncEvents/AsyncEvent`2.cs
Labels: bug, core, v5.x

#1562 Fix the poor XML that Aki butchered
  .gitignore
  DSharpPlus.Old.License
  Directory.Build.props
  Directory.Build.targets
Labels: enhancement, core, dependencies, v6.x
