Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-10, with the labels that each got.

#1636 consider actually keeping track of route hashes correctly
  DSharpPlus/Net/Rest/RateLimitPolicy.cs
Labels: bug, core, v5.x

#1639 embed titles can, in fact, be missing
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v5.x

#1626 Adding new MessageTypes
  DSharpPlus/Enums/Message/MessageType.cs
Labels: enhancement, core, v5.x

#1643 Fix issue with ratelimiting
  DSharpPlus/Net/Rest/RateLimitPolicy.cs
  DSharpPlus/Net/Rest/RestClient.cs
  Directory.Packages.props
Labels: bug, core

#1644 IAsyncEnumerble returns for GetAllMembersAsync and GetEventUsersAsync
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: enhancement, core

#1648 Fix Malformed urls
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/User/DiscordUser.cs
Labels: bug, core

#1649 Update bot_account.md
  docs/articles/basics/bot_account.md
Labels: docs

#1652 Add checks to ReplaceRolesAsnyc
  DSharpPlus/Entities/Guild/DiscordMember.cs
Labels: bug, core

#1654 [ci skip] expand the supported version matrix to nightly and v6
  docs/articles/preamble.md
Labels: docs

#1658 fix: rest request headers are not escaped
  DSharpPlus/Net/Rest/MultipartRestRequest.cs
  DSharpPlus/Net/Rest/RestRequest.cs
Labels: bug, core

#1664 Update docfx.json
  docs/docfx.json
Labels: enhancement, docs
