Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-07, with the labels that each got.

#1579 remove unused analyzer+update some deps
  DSharpPlus.CommandsNext/DSharpPlus.CommandsNext.csproj
  Directory.Build.props
Labels: v5.x, dependencies, tools

#1581 Update .gitignore
  .gitignore
  .vscode/settings.json
Labels: enhancement, core, v5.x, dependencies

#1582 Update DiscordExceptions to include the `JsonMessage` within the `Message` property.
  DSharpPlus/Exceptions/BadRequestException.cs
  DSharpPlus/Exceptions/DiscordException.cs
  DSharpPlus/Exceptions/NotFoundException.cs
  DSharpPlus/Exceptions/RateLimitException.cs
  DSharpPlus/Exceptions/RequestSizeException.cs
  DSharpPlus/Exceptions/ServerErrorException.cs
  DSharpPlus/Exceptions/UnauthorizedException.cs
Labels: enhancement, core, v5.x

#1583 Adding close codes 4001-4003 and 4005-4009 to auto reconnect logic
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
Labels: bug, core, v5.x

#1584 Renamed DiscordClient Events
  DSharpPlus.SlashCommands/SlashCommandsExtension.cs
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/EventArgs/SessionReadyEventArgs.cs
Labels: enhancement, core, v5.x

#1578 Pomelo support
  DSharpPlus.Test/TestBot.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/User/DiscordUser.cs
  DSharpPlus/Net/Abstractions/Transport/TransportUser.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v5.x

#1590 Correct DefaultAvatarUrl for non-Pomelo users
  DSharpPlus/Entities/User/DiscordUser.cs
Labels: bug, core, v5.x

#1595 Fix empty pages in pagination
  DSharpPlus.Interactivity/InteractivityExtension.cs
Labels: bug, enhancement, interactivity, v5.x

#1594 Fix NRE on Serialization of DiscordWebhooks
  DSharpPlus/Entities/Channel/DiscordPartialChannel.cs
  DSharpPlus/Entities/Webhook/DiscordWebhook.cs
  DSharpPlus/Net/Serialization/DiscordForumChannelJsonConverter.cs
Labels: bug, core, v5.x

#1596 Add missing DiscordClients on Event args
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bug, core, v5.x

#1587 Re-added a flag that I had deleted + headers formatting.
  DSharpPlus/Enums/User/UserFlags.cs
  DSharpPlus/Formatter.cs
Labels: enhancement, core, v5.x

#1597 the safety alerts channel ID is nullable, but not handled as such.
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: bug, core, v5.x
