Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-08, with the labels that each got.

#1600 Add a constructor to DefaultReaction and fix incorrect DefaultReaction JsonProperty name
  DSharpPlus/Entities/Channel/Thread/Forum/DefaultReaction.cs
  DSharpPlus/Entities/Channel/Thread/Forum/DiscordForumChannel.cs
Labels: bug, core, v5.x

#1586 Auditlog cleanup and update
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Entities/AuditLogs/AuditLogActionCategory.cs
  DSharpPlus/Entities/AuditLogs/AuditLogActionType.cs
  DSharpPlus/Entities/AuditLogs/AuditLogParser.cs
  DSharpPlus/Entities/AuditLogs/DiscordAuditLogEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogApplicationCommandPermissionEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogAutoModerationExecutedEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogAutoModerationRuleEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogBanEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogBotAddEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogChannelEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogEmojiEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogGuildEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogGuildScheduledEventEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogIntegrationEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogInviteEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogKickEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberDisconnectEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberMoveEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberUpdateEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMessageEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMessagePinEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogOverwriteEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogPruneEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogRoleUpdateEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogStickerEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogThreadEventEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogWebhookEntry.cs
  DSharpPlus/Entities/AuditLogs/PropertyChange.cs
  DSharpPlus/Entities/DiscordAuditLogObjects.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/EventArgs/Guild/GuildAuditLogCreatedEventArgs.cs
  DSharpPlus/Net/Abstractions/AuditLogAbstractions.cs
Labels: enhancement, core, big-change, v5.x

#1603 remove deprecated events
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.Events.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
Labels: core, v5.x
