Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-12, with the labels that each got.

#1701 Remove explicit support for Sourcelink
  Directory.Build.props
  Directory.Packages.props
Labels: enhancement, docs, dependencies, tools

#1702 Remove explicit SourceLink def; Update deps
  Directory.Build.props
  Directory.Packages.props
Labels: enhancement, core, dependencies

#1703 Fix/sharded shared rest
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: bug, core

#1705 Use new DiscordClient ctor and some renaming for better readability
  DSharpPlus/Clients/DiscordShardedClient.cs
Labels: bug, core

#1707 Update emoji mappings to support Twemoji v15.0.2
  DSharpPlus/Entities/Emoji/DiscordEmoji.EmojiUtils.cs
Labels: enhancement, core

#1708 Remove restriction from ShardedLoggerFactory
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Logging/DefaultLoggerFactory.cs
  DSharpPlus/Logging/ShardedLoggerFactory.cs
Labels: bug, core

#1709 4.4.6 - DiscordShardedClient logger fix
  DSharpPlus.targets
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Logging/DefaultLoggerFactory.cs
  DSharpPlus/Logging/ShardedLoggerFactory.cs
Labels: bug, core

#1711 Refactor old DeleteMessagesAsync and add an overload to support usage of IAsyncEnumerable
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Exceptions/BulkDeleteFailedException.cs
Labels: enhancement, core
