Repository DSharpPlus/DSharpPlus, pull requests merged in 2023-09, with the labels that each got.

#1613 Add None to DiscordIntents enum
  DSharpPlus/DiscordIntents.cs
Labels: enhancement, core, docs, v5.x

#1615 Remove misleading xml doc
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
Labels: core, docs, v5.x

#1612 AuditlogParser update
  DSharpPlus/Entities/AuditLogs/AuditLogParser.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogAutoModerationRuleEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogChannelEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogGuildEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMessageEntry.cs
  DSharpPlus/Entities/AuditLogs/PropertyChange.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: enhancement, v5.x, audit-log

#1618 Move auditlogs to own namespace
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/AuditLogs/AuditLogActionCategory.cs
  DSharpPlus/Entities/AuditLogs/AuditLogActionType.cs
  DSharpPlus/Entities/AuditLogs/AuditLogParser.cs
  DSharpPlus/Entities/AuditLogs/DiscordAuditLogEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogApplicationCommandPermissionEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogAutoModerationExecutedEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogAutoModerationRuleEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogBanEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogBotAddEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogChannelEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogEmojiEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogGuildEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogGuildScheduledEventEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogIntegrationEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogInviteEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogKickEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberDisconnectEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberMoveEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMemberUpdateEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMessageEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogMessagePinEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogOverwriteEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogPruneEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogRoleUpdateEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogStickerEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogThreadEventEntry.cs
  DSharpPlus/Entities/AuditLogs/Entries/DiscordAuditLogWebhookEntry.cs
  DSharpPlus/Entities/AuditLogs/PropertyChange.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/EventArgs/Guild/GuildAuditLogCreatedEventArgs.cs
  DSharpPlus/Net/Abstractions/AuditLogAbstractions.cs
Labels: enhancement, v5.x, audit-log

#1622 Yet another infrastructure update
  .github/workflows/publish_nightly_master.yml
  .github/workflows/publish_release_master.yml
  DSharpPlus.CommandsNext/DSharpPlus.CommandsNext.csproj
  DSharpPlus.Interactivity/DSharpPlus.Interactivity.csproj
  DSharpPlus.Lavalink/DSharpPlus.Lavalink.csproj
  DSharpPlus.Rest/DSharpPlus.Rest.csproj
  DSharpPlus.SlashCommands/DSharpPlus.SlashCommands.csproj
  DSharpPlus.VoiceNext/DSharpPlus.VoiceNext.csproj
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/DSharpPlus.csproj.DotSettings
  Directory.Build.props
  Directory.Packages.props
  tools/AutoUpdateChannelDescription/DSharpPlus.Tools.AutoUpdateChannelDescription.csproj
Labels: enhancement, core, big-change, v5.x, dependencies

#1619 Major DiscordShardedClient update/maintaining
  DSharpPlus.sln
  DSharpPlus/Clients/DiscordShardedClient.Events.cs
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Properties/AssemblyProperties.cs
  Directory.Packages.props
  tools/DSharpPlus.Tools.ShardedEventHandlingGen/DSharpPlus.Tools.ShardedEventHandlingGen.csproj
  tools/DSharpPlus.Tools.ShardedEventHandlingGen/Program.cs
Labels: enhancement, core, big-change, v5.x

#1608 clean up automod entities
  .gitignore
  DSharpPlus/Entities/AutoModeration/Action/DiscordAutoModerationActionExecution.cs
  DSharpPlus/Entities/AutoModeration/DiscordAutoModerationRule.cs
  DSharpPlus/Entities/AutoModeration/DiscordRuleTriggerMetadata.cs
Labels: enhancement, core, v5.x

#1630 Return the source exception within the CommandErrored event.
  DSharpPlus.CommandsNext/Entities/Command.cs
Labels: enhancement, commandsnext, v5.x

#1629 Add overloads for AddFile to support additional scenarios
  DSharpPlus/Entities/BaseDiscordMessageBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageFile.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, v5.x

#1627 action updates
  .github/workflows/docs.yml
  .github/workflows/publish_nightly_master.yml
  .github/workflows/publish_release_master.yml
Labels: enhancement, tools

#1620 Added support for sending messages in Stage type channels
  DSharpPlus/Utilities.cs
Labels: enhancement, v5.x

#1624 consolidate and improve internal rest infrastructure
  .editorconfig
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordClient.WebSocket.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/Entities/AutoModeration/DiscordAutoModerationRule.cs
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Channel/DiscordDmChannel.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Overwrite/DiscordOverwrite.cs
  DSharpPlus/Entities/Channel/Stage/DiscordStageInstance.cs
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
  DSharpPlus/Entities/Channel/Thread/Forum/DiscordForumChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/Guild/DiscordRole.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Invite/DiscordInvite.cs
  DSharpPlus/Entities/Webhook/DiscordWebhook.cs
  DSharpPlus/Exceptions/BadRequestException.cs
  DSharpPlus/Exceptions/DiscordException.cs
  DSharpPlus/Exceptions/NotFoundException.cs
  DSharpPlus/Exceptions/RateLimitException.cs
  DSharpPlus/Exceptions/RequestSizeException.cs
  DSharpPlus/Exceptions/ServerErrorException.cs
  DSharpPlus/Exceptions/UnauthorizedException.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestThreadPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestUserPayloads.cs
  DSharpPlus/Net/Abstractions/Rest/RestWebhookPayloads.cs
  DSharpPlus/Net/Rest/BaseRestRequest.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
  DSharpPlus/Net/Rest/IRestRequest.cs
  DSharpPlus/Net/Rest/MultipartRestRequest.cs
  DSharpPlus/Net/Rest/MultipartWebRequest.cs
  DSharpPlus/Net/Rest/RateLimitBucket.cs
  DSharpPlus/Net/Rest/RateLimitPolicy.cs
  DSharpPlus/Net/Rest/RestClient.cs
  DSharpPlus/Net/Rest/RestRequest.cs
  DSharpPlus/Net/Rest/RestRequestMethod.cs
  DSharpPlus/Net/Rest/RestResponse.cs
  DSharpPlus/Net/Rest/SessionBucket.cs
  DSharpPlus/QueryUriBuilder.cs
  DSharpPlus/Utilities.cs
  Directory.Packages.props
  tools/AutoUpdateChannelDescription/Program.cs
Labels: core, big-change, v5.x

#1631 fix two spots where we don't actually upload files
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core, v5.x
