Repository DSharpPlus/DSharpPlus, pull requests merged in 2024-02, with the labels that each got.

#1732 Expose the connection state of the client
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Net/WebSocket/IWebSocketClient.cs
  DSharpPlus/Net/WebSocket/WebSocketClient.cs
Labels: enhancement, core

#1737 Move optional parameter logic into base command processor
  DSharpPlus.Commands/Processors/BaseCommandProcessor/BaseCommandProcessor.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
Labels: bug, commands

#1738 Add DiscordThreadChannelMetadata#IsInvitable
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannelMetadata.cs
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Models/ThreadChannelEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#1739 Add fetching guilds over rest
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#1741 Send Flags when creating a message with a Messagebuilder
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core

#1736 Update AUCD to reload DocBot
  .github/workflows/build-commit.yml
  .github/workflows/release.yml
  tools/AutoUpdateChannelDescription/Program.cs
Labels: enhancement, docs, tools

#1745 Pass the parameter description instead of the command description
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
Labels: bug, commands

#1746 Update dependencies
  Directory.Packages.props
Labels: enhancement, core, dependencies, commands

#1744 send default member permissions as strings
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Net/Abstractions/Rest/RestApplicationCommandPayloads.cs
  DSharpPlus/Net/Serialization/DiscordPermissionsAsStringJsonConverter.cs
Labels: bug, core

#1747 DiscordMessageBuilder: MentionedUsers is not null on copy
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
Labels: bug, core

#1751 Check for found commands after searching nested classes and methods
  DSharpPlus.Commands/Trees/CommandBuilder.cs
Labels: bug, commands

#1752 fixes DiscordMessage.JumpLink which i previously broke
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
Labels: bug, core

#1753 fixes one potential edge case in ratelimiting
  DSharpPlus/Net/Rest/RateLimitBucket.cs
Labels: bug, core

#1755 fix nullability annotations for Optional<T>
  src/core/DSharpPlus.Internal.Models/Serialization/Converters/OptionalConverter.cs
  src/core/DSharpPlus.Shared/Optional`1.cs
Labels: enhancement, core

#1756 Allow. For. Component. Indexing.
  DSharpPlus/Entities/Interaction/Components/DiscordActionRowComponent.cs
Labels: enhancement, core

#1759 un-annotate DiscordMessage.Content
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
Labels: enhancement, core

#1749 factor localization logic out of the attribute
  DSharpPlus.Commands/Processors/MessageCommands/MessageCommandProcessor.cs
  DSharpPlus.Commands/Processors/SlashCommands/Attributes/InteractionLocalizerAttribute.cs
  DSharpPlus.Commands/Processors/SlashCommands/Attributes/SlashLocalizerAttribute.cs
  DSharpPlus.Commands/Processors/SlashCommands/Localization/DiscordLocale.cs
  DSharpPlus.Commands/Processors/SlashCommands/Localization/IInteractionLocalizer.cs
  DSharpPlus.Commands/Processors/SlashCommands/Localization/LocalesHelper.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
  DSharpPlus.Commands/Processors/UserCommands/UserCommandProcessor.cs
Labels: enhancement, commands

#1750 rename a bunch of things from slash- to interaction-
  DSharpPlus.Commands/Converters/ByteConverter.cs
  DSharpPlus.Commands/Converters/DateTimeOffsetConverter.cs
  DSharpPlus.Commands/Converters/DiscordAttachmentConverter.cs
  DSharpPlus.Commands/Converters/DiscordChannelConverter.cs
  DSharpPlus.Commands/Converters/DiscordEmojiConverter.cs
  DSharpPlus.Commands/Converters/DiscordMemberConverter.cs
  DSharpPlus.Commands/Converters/DiscordMessageConverter.cs
  DSharpPlus.Commands/Converters/DiscordRoleConverter.cs
  DSharpPlus.Commands/Converters/DiscordThreadChannelConverter.cs
  DSharpPlus.Commands/Converters/DiscordUserConverter.cs
  DSharpPlus.Commands/Converters/DoubleConverter.cs
  DSharpPlus.Commands/Converters/EnumArgumentConverter.cs
  DSharpPlus.Commands/Converters/FloatConverter.cs
  DSharpPlus.Commands/Converters/Int16Converter.cs
  DSharpPlus.Commands/Converters/Int32Converter.cs
  DSharpPlus.Commands/Converters/Int64Converter.cs
  DSharpPlus.Commands/Converters/SByteConverter.cs
  DSharpPlus.Commands/Converters/StringConverter.cs
  DSharpPlus.Commands/Converters/TimeSpanConverter.cs
  DSharpPlus.Commands/Converters/UInt16Converter.cs
  DSharpPlus.Commands/Converters/UInt32Converter.cs
  DSharpPlus.Commands/Converters/UInt64Converter.cs
  DSharpPlus.Commands/Processors/SlashCommands/InteractionConverterContext.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
Labels: enhancement, commands

#1760 `dotnet format`
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/ContextChecks/RequireNsfwCheck.cs
  DSharpPlus.Commands/ICommandExecutor.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
Labels: enhancement, commands

#1761 move CommandContext.
  DSharpPlus.Commands/CommandContext.cs
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/ContextChecks/ContextCheckMapEntry.cs
  DSharpPlus.Commands/ContextChecks/DirectMessageUsageCheck.cs
  DSharpPlus.Commands/ContextChecks/IContextCheck.cs
  DSharpPlus.Commands/ContextChecks/RequireApplicationOwnerCheck.cs
  DSharpPlus.Commands/ContextChecks/RequireGuildCheck.cs
  DSharpPlus.Commands/ContextChecks/RequireNsfwCheck.cs
  DSharpPlus.Commands/ContextChecks/RequirePermissionsCheck.cs
  DSharpPlus.Commands/EventArgs/CommandErroredEventArgs.cs
  DSharpPlus.Commands/EventArgs/CommandExecutedEventArgs.cs
  DSharpPlus.Commands/ICommandExecutor.cs
  DSharpPlus.Commands/Processors/BaseCommandProcessor/BaseCommandProcessor.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandContext.cs
  DSharpPlus.Commands/Processors/TextCommands/ContextChecks/TextMessageReplyCheck.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandContext.cs
  DSharpPlus.Commands/Trees/CommandBuilder.cs
  DSharpPlus.Commands/Trees/CommandParameterBuilder.cs
Labels: enhancement, commands

#1764 Nuke `DiscordConfiguration#UseRelativeRatelimits`
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/DiscordConfiguration.cs
Labels: core

#1765 Wait for response when we dont have a hash for a route
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Net/Rest/RateLimitPolicy.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: bug, enhancement, core

#1766 update polly and update how we use the API
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/RateLimitOptions.cs
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
  DSharpPlus/Net/Rest/RestClient.cs
  Directory.Packages.props
Labels: enhancement, core

#1767 fix the ratelimiter
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Net/Rest/PreemptiveRatelimitException.cs
  DSharpPlus/Net/Rest/RateLimitBucket.cs
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: bug, core

#1772 make sure we don't mark ratelimits as pending if we don't intend to update them
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
Labels: bug, core

#1773 kills an allocation in parsing the response for good measure
  DSharpPlus/Net/Rest/RateLimitBucket.cs
  DSharpPlus/Net/Rest/RateLimitCandidateBucket.cs
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
Labels: enhancement, core

#1775 Return the message on editResponse or editFollowup
  DSharpPlus.Commands/CommandContext.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandContext.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandContext.cs
Labels: enhancement, commands

#1778 fixes checks in general and RequireApplicationOwnerCheck in specific
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/ContextChecks/RequireApplicationOwnerCheck.cs
Labels: bug, commands

#1777 Fix 'HocusPocus' being turned into '_hocus_pocus' instead of 'hocus_pocus'
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
Labels: bug, commands

#1779 Polly dont support -1 as infinite
  DSharpPlus/Net/Rest/RestClient.cs
Labels: bug, core

#1780 Rest trace ids
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
  DSharpPlus/Net/Rest/RestClient.cs
Labels: enhancement, core

#1784 Allow for attachments to be grabbed from replies
  DSharpPlus.Commands/Converters/DiscordAttachmentConverter.cs
Labels: enhancement, commands

#1785 Add client to guilds for RestClients
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core
