Repository DSharpPlus/DSharpPlus, pull requests merged in 2024-01, with the labels that each got.

#1714 Correct disposal of underlying streams used in the messagebuilder
  DSharpPlus/Entities/BaseDiscordMessageBuilder.cs
Labels: bug, core

#1715 Added missing method for kicking members for `DiscordGuild.cs`.
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: enhancement, core

#1718 address TimeSpan Too Long errors thrown from using absolute instead of relative resets
  DSharpPlus/Net/Rest/RateLimitBucket.cs
Labels: bug, core

#1717 Added missing channel type.
  DSharpPlus/Enums/Channel/ChannelType.cs
Labels: enhancement, core, docs

#1719 Use new rest infra in DiscordShardedClient init
  DSharpPlus/Clients/DiscordShardedClient.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#1720 Mark `VoiceNextExtension.GetConnection` return as possible `null` value
  DSharpPlus.VoiceNext/DiscordClientExtensions.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
Labels: enhancement, voicenext, epic-nullability

#1722 Expose hidden properties found within DiscordVoiceState
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
Labels: enhancement, core, docs

#1723 Remove duplicate deps
  Directory.Packages.props
Labels: dependencies

#1724 annotate embed code for nullability
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.Interactivity/EventHandling/Paginator.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Entities/Channel/Message/DiscordAttachment.cs
  DSharpPlus/Entities/Channel/Message/DiscordMentions.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageActivity.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageInteraction.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageReference.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageSticker.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageStickerPack.cs
  DSharpPlus/Entities/Channel/Message/DiscordReaction.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbed.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedAuthor.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedBuilder.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedField.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedFooter.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedImage.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedProvider.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedThumbnail.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedVideo.cs
  DSharpPlus/Entities/Channel/Message/Mentions.cs
  DSharpPlus/Entities/DiscordUri.cs
  DSharpPlus/IMessageCacheProvider.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core, epic-nullability

#1725 Update Dependencies
  Directory.Packages.props
Labels: enhancement, commandsnext, core, slash-commands, dependencies

#1730 let users defer ephemerally
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandContext.cs
Labels: enhancement, commands

#1728 add AddCommands overloads for operating on single types
  DSharpPlus.Commands/CommandsExtension.cs
Labels: enhancement, commands
