Repository DSharpPlus/DSharpPlus, pull requests merged in 2024-10, with the labels that each got.

#2095 fix #2046
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bug, core

#2097 Have `DateTimeOffsetConverter` return the result in the `UTC` timezone.
  DSharpPlus.Commands/Converters/DateTimeOffsetConverter.cs
Labels: bug, enhancement, commands

#1998 Monetization support
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/EventHandlingBuilder.cs
  DSharpPlus/Entities/Application/DiscordApplication.cs
  DSharpPlus/Entities/Application/DiscordEntitlement.cs
  DSharpPlus/Entities/Application/DiscordEntitlementType.cs
  DSharpPlus/Entities/Application/DiscordStockKeepingUnit.cs
  DSharpPlus/Entities/Application/DiscordStockKeepingUnitFlags.cs
  DSharpPlus/Entities/Application/DiscordStockKeepingUnitType.cs
  DSharpPlus/Entities/Application/DiscordTestEntitlementOwnerType.cs
  DSharpPlus/EventArgs/Entitlement/EntitlementCreatedEventArgs.cs
  DSharpPlus/EventArgs/Entitlement/EntitlementDeletedEventArgs.cs
  DSharpPlus/EventArgs/Entitlement/EntitlementUpdatedEventArgs.cs
  DSharpPlus/Net/Abstractions/Rest/RestCreateTestEntitlementPayload.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Net/Rest/Endpoints.cs
Labels: enhancement, core, new-features

#2103 Prefer double backticks over single backticks so Discord can sanitize the backticks
  DSharpPlus.Commands/CommandsExtension.cs
Labels: bugfix, commands

#2104 Remove unnecessary null check
  DSharpPlus.Commands/Processors/SlashCommands/InteractionConverterContext.cs
Labels: bugfix, commands

#2102 Fix context menus
  DSharpPlus.Commands/Processors/MessageCommands/MessageCommandProcessor.cs
  DSharpPlus.Commands/Processors/SlashCommands/InteractionNamingPolicies/IInteractionNamingPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/InteractionNamingPolicies/KebabCaseNamingPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/InteractionNamingPolicies/LowercaseNamingPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/InteractionNamingPolicies/SnakeCaseNamingPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
  DSharpPlus.Commands/Processors/UserCommands/UserCommandProcessor.cs
Labels: bugfix, commands

#2098 Allow `RequireTextReply` on the first parameter
  DSharpPlus.Commands/Converters/BooleanConverter.cs
  DSharpPlus.Commands/Converters/ByteConverter.cs
  DSharpPlus.Commands/Converters/DateTimeOffsetConverter.cs
  DSharpPlus.Commands/Converters/DiscordAttachmentConverter.cs
  DSharpPlus.Commands/Converters/DiscordChannelConverter.cs
  DSharpPlus.Commands/Converters/DiscordEmojiConverter.cs
  DSharpPlus.Commands/Converters/DiscordMemberConverter.cs
  DSharpPlus.Commands/Converters/DiscordMessageConverter.cs
  DSharpPlus.Commands/Converters/DiscordRoleConverter.cs
  DSharpPlus.Commands/Converters/DiscordSnowflakeObjectConverter.cs
  DSharpPlus.Commands/Converters/DiscordThreadChannelConverter.cs
  DSharpPlus.Commands/Converters/DiscordUserConverter.cs
  DSharpPlus.Commands/Converters/DoubleConverter.cs
  DSharpPlus.Commands/Converters/EnumArgumentConverter.cs
  DSharpPlus.Commands/Converters/EnumArgumentConverter`1.cs
  DSharpPlus.Commands/Converters/FloatConverter.cs
  DSharpPlus.Commands/Converters/Int16Converter.cs
  DSharpPlus.Commands/Converters/Int32Converter.cs
  DSharpPlus.Commands/Converters/Int64Converter.cs
  DSharpPlus.Commands/Converters/SByteConverter.cs
  DSharpPlus.Commands/Converters/StringConverter.cs
  DSharpPlus.Commands/Converters/TimeSpanConverter.cs
  DSharpPlus.Commands/Converters/UInt16Converter.cs
  DSharpPlus.Commands/Converters/UInt32Converter.cs
  DSharpPlus.Commands/Converters/UInt64Converter.cs
  DSharpPlus.Commands/Processors/BaseCommandProcessor/BaseCommandProcessor.cs
  DSharpPlus.Commands/Processors/TextCommands/ConverterRequiresText.cs
  DSharpPlus.Commands/Processors/TextCommands/ITextArgumentConverter.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
  DSharpPlus.Commands/Processors/TextCommands/TextConverterContext.cs
Labels: bugfix, commands

#2105 improve logging of resumes and reconnects
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Net/Gateway/DefaultGatewayController.cs
  DSharpPlus/Net/Gateway/GatewayClient.cs
  DSharpPlus/Net/Gateway/IGatewayController.cs
  DSharpPlus/Net/Gateway/ReconnectingGatewayController.cs
Labels: bugfix, enhancement, core

#2106 Fix pagination for Get Guild Scheduled Event Users
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bugfix, core

#2107 fixes #1958
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/ContextChecks/RequireGuildCheck.cs
  DSharpPlus.Commands/Trees/CommandBuilder.cs
Labels: bugfix, commands

#1982 prepare for having alpha builds
  .github/workflows/build-alpha.yml
  .github/workflows/build-commit.yml
  Directory.Build.props
Labels: tools

#2109 comply with semver
  .github/workflows/build-commit.yml
Labels: tools

#2108 try to stream deserialization when we don't need to log anything
  DSharpPlus/Net/Gateway/GatewayClient.cs
  DSharpPlus/Net/Gateway/GatewayClientOptions.cs
  DSharpPlus/Net/Gateway/TransportFrame.cs
  DSharpPlus/Net/Gateway/TransportService.cs
Labels: enhancement, core

#2110 break semver again (complying with it broke the package lists)
  .github/workflows/build-commit.yml
  Directory.Build.props
Labels: tools

#1970 Add banner to ModifyCurrentUserAsync
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Net/Abstractions/Rest/RestUserPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#2111 Use a more precise error message for RespondWithModal
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandContext.cs
Labels: enhancement, commands

#2100 Added forwarded messages
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageReference.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageReferenceType.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageSnapshot.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageSnapshotContent.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  DSharpPlus/Utilities.cs
Labels: enhancement, core

#2112 Update outdated libs
  Directory.Packages.props
Labels: dependencies

#2113 Fix nullability on `DiscordUser`-based `Equals` methods/operators
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/User/DiscordUser.cs
Labels: core, epic-nullability

#2114 Text aliases on group commands no longer break subcommands
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
Labels: bugfix, commands

#2118 Removed `DiscordGuild.CurrentMember` `Lazy`
  DSharpPlus/Entities/Guild/DiscordGuild.cs
Labels: bugfix, core

#2119 Add `DiscordMember.IsTimedOut`
  DSharpPlus/Entities/Guild/DiscordMember.cs
Labels: enhancement, core

#2120 Add DiscordThreadChannel.AppliedTagIds property
  DSharpPlus/Entities/Channel/Thread/DiscordThreadChannel.cs
Labels: enhancement, core

#2122 wait and retry if we hit a 429 rather than abandoning
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus/Net/Rest/RateLimitStrategy.cs
  DSharpPlus/Net/Rest/RestClient.cs
  DSharpPlus/Net/Rest/RestClientOptions.cs
  DSharpPlus/Net/Rest/RetryableRatelimitException.cs
Labels: enhancement, core

#2123 support creating message forwards
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#2115 avoid bulk overwriting global commands
  DSharpPlus.Commands/Processors/SlashCommands/RemoteRecordRetentionPolicies/DefaultRemoteRecordRetentionPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/RemoteRecordRetentionPolicies/IRemoteRecordRetentionPolicy.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandConfiguration.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.Remote.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashLogging.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.WeakEquals.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandType.cs
  DSharpPlus/Net/Models/ApplicationCommandEditModel.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bugfix, discord-issue, commands

#2131 avoid calling ICU for commands that aren't actually ever localized
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
Labels: enhancement, commands

#2132 add an overload to allow registering Type objects of event handlers
  DSharpPlus/Clients/EventHandlerCollection.cs
  DSharpPlus/Clients/EventHandlingBuilder.cs
Labels: enhancement, core

#2133 fix #2129
  DSharpPlus.Commands/ProcessorInvokingHandlers.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.Remote.cs
Labels: bugfix, commands

#2124 convenience properties for avatar hashes and urls
  DSharpPlus/Entities/Guild/DiscordMember.cs
Labels: enhancement, core

#2134 fix commands not fetching localization
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
Labels: bugfix, commands

#2135 unescape unicode in localizations received from discord
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.WeakEquals.cs
Labels: bugfix, commands

#2143 fix(core): Make default permission for app commands UseApplicationCom…
  DSharpPlus.Commands/Processors/MessageCommands/MessageCommandProcessor.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/UserCommands/UserCommandProcessor.cs
Labels: bugfix, core

#2144 fix #2140
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bugfix, core

#2146 Fix SnowflakeObjectConverter
  DSharpPlus.Commands/Converters/DiscordRoleConverter.cs
Labels: bugfix, commands

#2148 Fix leaking result on required remaining text (Attempt 2)
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
Labels: bugfix, commands
