Repository DSharpPlus/DSharpPlus, pull requests merged in 2024-12, with the labels that each got.

#2204 Fix send/create message descriptions
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: core, docs

#2205 fixes creating a permission overwrite
  DSharpPlus/Net/Abstractions/Rest/RestChannelPayloads.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bugfix, core

#2207 Added CreatorId field to DiscordScheduledGuildEvent
  DSharpPlus/Entities/Guild/ScheduledEvents/DiscordScheduledGuildEvent.cs
Labels: bugfix, core

#2206 Only update user cache in interactions if guild is in cache
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bugfix, core

#2211 fix: tokens containing underscores not being anonymized
  DSharpPlus/Logging/AnonymizationUtilities.cs
Labels: bugfix, core

#2209 Miscellaneous updates and fixes to the docs
  docs/articles/basics/bot_account.md
  docs/articles/commands/processors/slash_commands/choice_provider_vs_autocomplete.md
  docs/articles/commands/processors/slash_commands/naming_policies.md
  docs/articles/migration/4x_to_5x.md
  docs/articles/migration/slashcommands_to_commands.md
  docs/images/basics_bot_account_01.png
  docs/images/basics_bot_account_02.png
  docs/images/basics_bot_account_03.png
  docs/images/basics_bot_account_04.png
  docs/images/basics_bot_account_05.png
  docs/images/basics_bot_account_06.png
  docs/images/basics_bot_account_07.png
  docs/images/basics_bot_account_08.png
  docs/images/basics_bot_account_09.png
  docs/images/basics_bot_account_10.png
Labels: enhancement, docs

#2214 Add DiscordClient to application owner
  DSharpPlus/Entities/Application/DiscordApplication.cs
Labels: bugfix, core

#2212 properly report application command registration errors
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/Exceptions/ChoiceProviderFailedException.cs
  DSharpPlus.Commands/Exceptions/CommandRegistrationFailedException.cs
  DSharpPlus.Commands/Processors/SlashCommands/ArgumentModifiers/SlashChoiceProviderAttribute.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.cs
Labels: enhancement, commands

#2000 rework gateway compression
  DSharpPlus/Clients/DiscordClientBuilder.cs
  DSharpPlus/Clients/MultiShardOrchestrator.cs
  DSharpPlus/Clients/SingleShardOrchestrator.cs
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/DiscordConfiguration.cs
  DSharpPlus/Extensions/ServiceCollectionExtensions.InternalSetup.cs
  DSharpPlus/Extensions/ServiceCollectionExtensions.cs
  DSharpPlus/GatewayCompressionLevel.cs
  DSharpPlus/Net/Abstractions/Gateway/GatewayIdentifyResume.cs
  DSharpPlus/Net/Gateway/Compression/IPayloadDecompressor.cs
  DSharpPlus/Net/Gateway/Compression/NullDecompressor.cs
  DSharpPlus/Net/Gateway/Compression/Zlib/ZlibPayloadDecompressor.cs
  DSharpPlus/Net/Gateway/Compression/Zlib/ZlibStreamDecompressor.cs
  DSharpPlus/Net/Gateway/Compression/Zlib/ZlibWrapper.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdDecompressor.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdErrorCode.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdInputBuffer.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdInterop.Bindings.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdInterop.cs
  DSharpPlus/Net/Gateway/Compression/Zstd/ZstdOutputBuffer.cs
  DSharpPlus/Net/Gateway/GatewayClient.cs
  DSharpPlus/Net/Gateway/TransportService.cs
  DSharpPlus/Net/WebSocket/PayloadDecompressor.cs
  docs/articles/advanced_topics/compression.md
  docs/articles/toc.yml
Labels: enhancement, core

#2215 Fixed incorrect link in docs.
  docs/articles/basics/bot_account.md
Labels: core, docs

#2216 Improved preamble article.
  docs/articles/preamble.md
Labels: enhancement, docs

#2217 Potential fix for Gateway client reconnecting when it was explicitly told to disconnect.
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bugfix, core

#2218 improve zstd auto detection
  DSharpPlus/Extensions/ServiceCollectionExtensions.InternalSetup.cs
  docs/articles/advanced_topics/compression.md
Labels: enhancement, core

#2221 Add create test and consume entitlement methods to DiscordApplication
  DSharpPlus/Entities/Application/DiscordApplication.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#2222 Add test entitlement deletion
  DSharpPlus/Entities/Application/DiscordApplication.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core
