Repository DSharpPlus/DSharpPlus, pull requests merged in 2024-08, with the labels that each got.

#2058 Configure contextmenu processors before slashcommand processor
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/Processors/MessageCommands/MessageCommandProcessor.cs
  DSharpPlus.Commands/Processors/UserCommands/UserCommandProcessor.cs
Labels: bug, commands

#2059 pass the minimum log level when using DiscordClientBuilder.SetLogLevel
  DSharpPlus/Clients/DiscordClientBuilder.cs
Labels: bug, core

#2061 Split Text Command Searching Logic
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
Labels: enhancement, commands

#2064 Set the guild id on the message when we have it in the cache
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: bug, core

#2067 fix the event handler scope being disposed prematurely
  DSharpPlus/Clients/DefaultEventDispatcher.cs
Labels: bug, core

#2068 expose total and connected shard counts on IShardOrchestrator
  DSharpPlus/Clients/IShardOrchestrator.cs
  DSharpPlus/Clients/MultiShardOrchestrator.cs
  DSharpPlus/Clients/SingleShardOrchestrator.cs
Labels: enhancement, core

#2069 add a few more control events
  DSharpPlus.Commands/RefreshEventHandler.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/EventArgs/ClientStartedEventArgs.cs
  DSharpPlus/EventArgs/ClientStoppedEventArgs.cs
  DSharpPlus/EventArgs/SessionCreatedEventArgs.cs
  DSharpPlus/EventArgs/SessionResumedEventArgs.cs
  DSharpPlus/Net/Abstractions/Gateway/GatewayPayload.cs
  DSharpPlus/Net/Abstractions/Gateway/ShardIdContainingGatewayPayload.cs
  DSharpPlus/Net/Gateway/DefaultGatewayController.cs
  DSharpPlus/Net/Gateway/GatewayClient.cs
  DSharpPlus/Net/Gateway/IGatewayClient.cs
  DSharpPlus/Net/Gateway/IGatewayController.cs
  DSharpPlus/Net/Gateway/ReconnectingGatewayController.cs
Labels: enhancement, core

#2070 expose the guild IDs in SessionCreated
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/EventArgs/SessionCreatedEventArgs.cs
Labels: enhancement, core

#2071 Add get role endpoint
  DSharpPlus.Commands/Converters/DiscordRoleConverter.cs
  DSharpPlus.CommandsNext/CommandsNextExtension.cs
  DSharpPlus.CommandsNext/Converters/EntityConverters.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/AuditLogs/AuditLogParser.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessage.cs
  DSharpPlus/Entities/Channel/Overwrite/DiscordOverwrite.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
  obsolete/DSharpPlus.SlashCommands/SlashCommandsExtension.cs
Labels: enhancement, core, new-features

#2080 Fix SlashCommandsExtension IServiceProvider
  obsolete/DSharpPlus.SlashCommands/ExtensionMethods.cs
  obsolete/DSharpPlus.SlashCommands/SlashCommandConfiguration.cs
  obsolete/DSharpPlus.SlashCommands/SlashCommandsExtension.cs
Labels: bug, obsolete: slash-commands

#2082 Add ApproximateUserInstallCount
  DSharpPlus/Entities/Application/DiscordApplication.cs
  DSharpPlus/Net/Abstractions/Transport/TransportApplication.cs
Labels: enhancement, core
