Repository DSharpPlus/DSharpPlus, pull requests merged in 2025-09, with the labels that each got.

#2371 Refactor collections to use IReadOnlyList instead of ReadOnlyCollection
  DSharpPlus.CommandsNext/Attributes/AliasesAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequireRolesAttribute.cs
  DSharpPlus.CommandsNext/Entities/Builders/CommandBuilder.cs
  DSharpPlus.CommandsNext/Entities/Builders/CommandGroupBuilder.cs
  DSharpPlus.CommandsNext/Entities/Builders/CommandOverloadBuilder.cs
  DSharpPlus.CommandsNext/Entities/CommandArgument.cs
  DSharpPlus.CommandsNext/Exceptions/ChecksFailedException.cs
  DSharpPlus.CommandsNext/Exceptions/DuplicateOverloadException.cs
  DSharpPlus.Interactivity/EventHandling/EventWaiter.cs
  DSharpPlus.Interactivity/EventHandling/Poller.cs
  DSharpPlus.Interactivity/EventHandling/ReactionCollector.cs
  DSharpPlus.Interactivity/Extensions/MessageExtensions.cs
  DSharpPlus.Interactivity/InteractivityExtension.cs
  DSharpPlus.VoiceNext/AudioFormat.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Entities/Application/DiscordApplication.cs
  DSharpPlus/Entities/AuditLogs/AuditLogParser.cs
  DSharpPlus/Entities/Channel/Message/Embed/DiscordEmbedBuilder.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.cs
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommandOption.cs
  DSharpPlus/EventArgs/Guild/Member/GuildMemberUpdatedEventArgs.cs
  DSharpPlus/Net/Rest/DiscordRestApiClient.cs
Labels: enhancement, core

#2375 Documentation changes for choice provider vs. autocomplete provider
  docs/articles/commands/processors/slash_commands/choice_provider_vs_autocomplete.md
Labels: docs

#2374 Support for selects in modals
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandContext.cs
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
  DSharpPlus/Entities/Interaction/Components/DiscordComponentType.cs
  DSharpPlus/Entities/Interaction/Components/DiscordLabelComponent.cs
  DSharpPlus/Entities/Interaction/Components/Selects/BaseDiscordSelectComponent.cs
  DSharpPlus/Entities/Interaction/DiscordHttpInteraction.cs
  DSharpPlus/Entities/Interaction/DiscordInteraction.cs
  DSharpPlus/Entities/Interaction/DiscordInteractionResponseBuilder.cs
  DSharpPlus/Entities/Interaction/DiscordModalBuilder.cs
  DSharpPlus/Net/Rest/DiscordRestApiClient.cs
  DSharpPlus/Net/Serialization/DiscordComponentJsonConverter.cs
Labels: enhancement, core, new-features

#2377 fix velvetware and support all select types in modals
  DSharpPlus/Entities/Interaction/Components/DiscordComponentType.cs
  DSharpPlus/Entities/Interaction/Components/DiscordLabelComponent.cs
  DSharpPlus/Entities/Interaction/Components/DiscordTextInputComponent.cs
  DSharpPlus/Entities/Interaction/Components/Selects/BaseDiscordSelectComponent.cs
  DSharpPlus/Entities/Interaction/DiscordModalBuilder.cs
  DSharpPlus/EventArgs/Interaction/ChannelSelectMenuModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/IModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/MentionableSelectMenuModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/ModalSubmittedEventArgs.cs
  DSharpPlus/EventArgs/Interaction/RoleSelectMenuModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/SelectMenuModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/TextInputModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/UnknownComponentModalSubmission.cs
  DSharpPlus/EventArgs/Interaction/UserSelectMenuModalSubmission.cs
  DSharpPlus/Net/Serialization/DiscordComponentJsonConverter.cs
Labels: bugfix, enhancement, core

#2379 remove label from the text input component
  DSharpPlus/Entities/Interaction/Components/DiscordTextInputComponent.cs
Labels: bugfix, core

#2380 Update slash command verification to allow changing interaction types
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.Remote.cs
Labels: bugfix, commands

#2381 remove legacy text input functionality from the message builder
  DSharpPlus/Entities/BaseDiscordMessageBuilder.cs
Labels: enhancement, core
