Repository DSharpPlus/DSharpPlus, pull requests merged in 2025-03, with the labels that each got.

#2254 Change the constructors to be `object?` for easier pattern matching
  DSharpPlus/Entities/Interaction/Application/DiscordAutoCompleteChoice.cs
Labels: enhancement, core

#2233 `RequirePermissions`: Use `DiscordPermissions`
  DSharpPlus.Commands/ContextChecks/RequirePermissionsAttribute.cs
  DSharpPlus.Commands/ContextChecks/RequirePermissionsCheck.cs
  DSharpPlus.Commands/Processors/MessageCommands/MessageCommandProcessor.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/UserCommands/UserCommandProcessor.cs
Labels: enhancement, core

#2256 Allow the user to see which prefix was used when invoking a command
  DSharpPlus.Commands/Processors/TextCommands/TextCommandContext.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
  DSharpPlus.Commands/Processors/TextCommands/TextConverterContext.cs
Labels: enhancement, commands

#2257 HeartbeatAsync Race Condition Causes ObjectDisposedException
  DSharpPlus/Net/Gateway/TransportService.cs
Labels: bugfix, core

#2258 Restart heartbeat task during resumes
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bugfix

#2264 Revert "Restart heartbeat task during resumes"
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bugfix, core

#2273 Fix nested group commands
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
  DSharpPlus.Commands/Trees/Command.cs
  DSharpPlus.Commands/Trees/CommandBuilder.cs
Labels: bugfix, commands

#2268 Update dependencies
  Directory.Packages.props
Labels: core, dependencies

#2275 Fix GetMessagesAsync when provinding no before, after or around
  DSharpPlus/Entities/Channel/DiscordChannel.cs
Labels: bugfix, core

#2276 remove unnecessary dependency references
  DSharpPlus.CommandsNext/DSharpPlus.CommandsNext.csproj
  obsolete/DSharpPlus.SlashCommands/DSharpPlus.SlashCommands.csproj
Labels: dependencies

#2274 feat(interactivity): Improve interaction rejection messages
  DSharpPlus.Interactivity/EventHandling/ComponentBased/ComponentEventWaiter.cs
  DSharpPlus.Interactivity/InteractivityConfiguration.cs
Labels: interactivity, new-features

#2277 `DSharpPlus.Commands`: Fix naming consistency of subcommand
  DSharpPlus.Commands/CommandsExtension.cs
  DSharpPlus.Commands/Processors/SlashCommands/SlashCommandProcessor.Registration.cs
  DSharpPlus.Commands/Processors/TextCommands/TextCommandProcessor.cs
  DSharpPlus.Commands/Trees/Command.cs
  DSharpPlus.Commands/Trees/CommandBuilder.cs
Labels: commands
