Repository DSharpPlus/DSharpPlus, pull requests merged in 2025-07, with the labels that each got.

#2348 feat(user): add primary guild support for users and related properties
  DSharpPlus/Entities/Guild/DiscordMember.cs
  DSharpPlus/Entities/User/DiscordUser.cs
  DSharpPlus/Entities/User/DiscordUserPrimaryGuild.cs
  DSharpPlus/Net/Abstractions/Transport/TransportUser.cs
Labels: core, new-features

#2354 Refactor format detection and fix initial value
  DSharpPlus/InlineMediaTool.cs
Labels: bugfix, enhancement, core

#2357 add support for handling poll completion messages
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Clients/EventHandlingBuilder.cs
  DSharpPlus/Entities/Channel/Message/DiscordMessageType.cs
  DSharpPlus/Entities/Channel/Message/Poll/DiscordPollCompletionMessage.cs
  DSharpPlus/EventArgs/Message/MessagePollCompletedEventArgs.cs
Labels: enhancement, core
