Repository DSharpPlus/DSharpPlus, pull requests merged in 2025-05, with the labels that each got.

#2311 Voicestate overhaul and adding voicestate rest endpoint
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
  DSharpPlus/EventArgs/Voice/VoiceStateUpdatedEventArgs.cs
  DSharpPlus/Net/Rest/DiscordApiClient.cs
Labels: enhancement, core

#2312 fix: use base class for selects, oops.
  DSharpPlus/Entities/BaseDiscordMessageBuilder.cs
Labels: bugfix

#2313 fix: associate Discord instance with http interaction in interactionE…
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bugfix, core

#2314 Introduce `NullShardOrchestrator`
  DSharpPlus/Clients/NullShardOrchestrator.cs
  DSharpPlus/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement, core

#2315 feat: reintroduce user, guild and channel directly on the VoiceStateU…
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
  DSharpPlus/EventArgs/Voice/VoiceStateUpdatedEventArgs.cs
Labels: enhancement, core

#2308 move rest-only access into corelib
  DSharpPlus.Rest/DSharpPlus.Rest.csproj
  DSharpPlus.Rest/DiscordRestClient.cs
  DSharpPlus.sln
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Clients/DiscordClient.cs
  DSharpPlus/Clients/DiscordClientBuilder.cs
  DSharpPlus/Clients/DiscordRestApiClientFactory.cs
  DSharpPlus/Clients/DiscordWebhookClient.cs
  DSharpPlus/Clients/MultiShardOrchestrator.cs
  DSharpPlus/Clients/OAuth2DiscordClient.cs
  DSharpPlus/Clients/SingleShardOrchestrator.cs
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/Entities/Channel/DiscordChannel.cs
  DSharpPlus/Entities/Guild/DiscordGuild.cs
  DSharpPlus/Entities/Guild/DiscordRole.cs
  DSharpPlus/Entities/Webhook/DiscordWebhook.cs
  DSharpPlus/Extensions/ServiceCollectionExtensions.InternalSetup.cs
  DSharpPlus/Extensions/ServiceCollectionExtensions.cs
  DSharpPlus/Logging/DefaultLogger.cs
  DSharpPlus/Net/Abstractions/Rest/DiscordChannelPosition.cs
  DSharpPlus/Net/Abstractions/Rest/DiscordRolePosition.cs
  DSharpPlus/Net/Abstractions/Rest/RestGuildPayloads.cs
  DSharpPlus/Net/Rest/DiscordRestApiClient.cs
  DSharpPlus/Net/Rest/RestClient.cs
  Directory.Packages.props
Labels: core, new-features

#2319 add a dependency on sodium to dsharpplus.http.aspnetcore
  DSharpPlus.Http.AspNetCore/DSharpPlus.Http.AspNetCore.csproj
  Directory.Packages.props
Labels: enhancement, http

#2154 Create an analyzer for DSharpPlus
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/DSharpPlus.Analyzers.Test.csproj
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/HasPermissionTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/MultipleOverwriteTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/ProcessorCheckTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/RegisterNestedClassesTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/SingleEntityGetTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/UseDiscordPermissionsTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/Utility.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers.Test/ValidGuildInstallablesTest.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/AnalyzerReleases.Shipped.md
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/AnalyzerReleases.Unshipped.md
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Commands/ProcessorCheckAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Commands/RegisterNestedClassesAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Commands/ValidGuildInstallablesAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Core/HasPermissionAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Core/MultipleOverwriteAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Core/SingleEntityGetRequestAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Core/UseDiscordPermissionsAnalyzer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/DSharpPlus.Analyzers.csproj
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Properties/launchSettings.json
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Resources.Designer.cs
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Resources.resx
  DSharpPlus.Analyzers/DSharpPlus.Analyzers/Utility.cs
  DSharpPlus.sln
  DSharpPlus/DSharpPlus.csproj
  DSharpPlus/Entities/DiscordPermissions.Enumeration.cs
  Directory.Packages.props
  README.md
  docs/articles/analyzers/commands.md
  docs/articles/analyzers/core.md
  docs/articles/toc.yml
  docs/filter_config.yml
Labels: enhancement, new-features, big-change, analyzer

#2321 Fix EditOriginalResponseAsync with CV2
  DSharpPlus/Net/Rest/DiscordRestApiClient.cs
Labels: bugfix, core, discord-issue

#2322 enable collection expressions for permissions
  DSharpPlus.CommandsNext/Attributes/RequireBotPermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequirePermissionsAttribute.cs
  DSharpPlus.CommandsNext/Attributes/RequireUserPermissionsAttribute.cs
  DSharpPlus.VoiceNext/VoiceNextExtension.cs
  DSharpPlus/Entities/DiscordPermission.cs
  DSharpPlus/Entities/DiscordPermissions.Arithmetics.cs
  DSharpPlus/Entities/DiscordPermissions.Enumeration.cs
  DSharpPlus/Entities/DiscordPermissions.Utility.cs
  DSharpPlus/Entities/DiscordPermissions.cs
  docs/articles/beyond_basics/permissions.md
  obsolete/DSharpPlus.SlashCommands/Built-in Checks/SlashRequireBotPermissionsAttribute.cs
  obsolete/DSharpPlus.SlashCommands/Built-in Checks/SlashRequirePermissionsAttribute.cs
  obsolete/DSharpPlus.SlashCommands/Built-in Checks/SlashRequireUserPermissionsAttribute.cs
Labels: enhancement, core

#2324 Use slnx instead of old sln
  DSharpPlus.sln
  DSharpPlus.slnx
  Directory.Build.props
Labels: enhancement, core

#2325 Expose UserId in DiscordVoiceState and readd quick access to ids in VoiceStateUpdatedEventArgs
  DSharpPlus/Entities/Voice/DiscordVoiceState.cs
  DSharpPlus/EventArgs/Voice/VoiceStateUpdatedEventArgs.cs
Labels: enhancement, core

#2328 restore the api docs to their rightful place
  docs/docfx.json
Labels: bugfix, docs

#2329 fix(core): Don't count action row components in CV1
  DSharpPlus/Entities/BaseDiscordMessageBuilder.cs
Labels: bugfix, core
