Repository DSharpPlus/DSharpPlus, pull requests merged in 2025-01, with the labels that each got.

#2223 Add debug symbols to build
  Directory.Build.props
Labels: enhancement

#2220 add a default-disabled option to prune unhandled gw events
  DSharpPlus/Net/Gateway/GatewayClient.cs
  DSharpPlus/Net/Gateway/GatewayClientOptions.cs
Labels: enhancement, core

#2227 Update GH Actions versions
  .github/workflows/build-commit.yml
Labels: tools

#2228 Keep all data in original json in ready payload object
  DSharpPlus/Clients/DiscordClient.Dispatch.cs
Labels: bugfix, core

#2224 conform to gateway spec errors rather than handling them with discord errors
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bugfix, core

#2230 fix a stray error message when encountering an invalid session in trying to resume
  DSharpPlus/Net/Gateway/GatewayClient.cs
Labels: bugfix, core

#2236 account for dm permissions when checking command equality
  DSharpPlus/Entities/Interaction/Application/DiscordApplicationCommand.WeakEquals.cs
Labels: bugfix, core, commands

#2238 Add missing DiscordClient to DiscordApplication
  DSharpPlus/Clients/BaseDiscordClient.cs
  DSharpPlus/Entities/Application/DiscordApplication.cs
Labels: bugfix, core

#2239 Fix skipCache logic in CreateDmChannelAsync
  DSharpPlus/Entities/User/DiscordUser.cs
Labels: bugfix, core
